import 'package:get/get_navigation/src/root/internacionalization.dart';

class Language extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en_US': {
      'Select your preferred language': 'Select your preferred language',
      'Login': 'Login',
      'Enter Your Email': 'Enter Your Email',
      'Please enter a valid email': 'Please enter a valid email',
      'Enter Your Password': 'Enter Your Password',
      'Password not be empty!': 'Password not be empty!',
      'Password must be greater than 5 character!':
      'Password must be greater than 5 character!',
      'Forgot Password?': 'Forgot Password?',
      'Forgot Password': 'Forgot Password',
      'Don’t have an account ?   ': 'Don’t have an account ?   ',
      'Sign Up': 'Sign Up',
      'Don’t worry! It happens. Please enter the email address associated with your account.':
      'Don’t worry! It happens. Please enter the email address associated with your account.',
      'Submit': 'Submit',
      'Reset Password': 'Reset Password',
      'Your new password must be different from previous used passwords.':
      'Your new password must be different from previous used passwords.',
      'Password': 'Password',
      'Confirm Password': 'Confirm Password',
      'Select Role': 'Select Role',
      'Freelancers': 'Freelancers',
      'Shop Owner': 'Shop Owner',
      'Already have an account ?   ': 'Already have an account ?   ',
      'Upload Selfie': 'Upload Selfie',
      'Take Selfie for starting Questionnaire':
      'Take Selfie for starting Questionnaire',
      'Take Selfie': 'Take Selfie',
      'Take / Upload': 'Take / Upload',
      'Upload from Gallery': 'Upload from Gallery',
      'Next': 'Next',
      'Scan Your ID': 'Scan Your ID',
      'Personal Details\nConfirmation': 'Personal Details\nConfirmation',
      'Mobile & Email\nConfirmation': 'Mobile & Email\nConfirmation',
      'Enter Verification\nCode': 'Enter Verification\nCode',
      'Scan Your License': 'Scan Your License',
      'License Details\nConfirmation': 'License Details\nConfirmation',
      'Confirm': 'Confirm',
      'Verify': 'Verify',
      'Back': 'Back',
      'Please confirm your\nPersonal Information':
      'Please confirm your\nPersonal Information',
      'ID Number': 'ID Number',
      'ID Number not be empty!': 'ID Number not be empty!',
      'Full Name': 'Full Name',
      'Full Name not be empty!': 'Full Name not be empty!',
      'Nationality': 'Nationality',
      'Nationality not be empty!': 'Nationality not be empty!',
      'Scan the back of your ': 'Scan the back of your ',
      'Emirates ID': 'Emirates ID',
      'Start Scanning': 'Start Scanning',
      'Card Number': 'Card Number',
      'Card Number not be empty!': 'Card Number not be empty!',
      'Please Place the back of your\nTrade License inside the frame':
      'Please Place the back of your\nTrade License inside the frame',
      'Scan License': 'Scan License',
      'Please Place the back of your\nEmirates ID inside the frame':
      'Please Place the back of your\nEmirates ID inside the frame',
      'Scan Card': 'Scan Card',
      'Date of Birth': 'Date of Birth',
      'Date of Birth not be empty!': 'Date of Birth not be empty!',
      'Expiry Date': 'Expiry Date',
      'Expiry Date not be empty!': 'Expiry Date not be empty!',
      'Gender': 'Gender',
      'Male': 'Male',
      'Female': 'Female',
      'Other': 'Other',
      'Gender not be empty!': 'Gender not be empty!',
      'Please provide your Mobile Phone Number and Email to continue':
      'Please provide your Mobile Phone Number and Email to continue',
      'Phone Number': 'Phone Number',
      'Email': 'Email',
      'Please enter the OTP Code\nwe sent you':
      'Please enter the OTP Code\nwe sent you',
      'I did not receive the OTP': 'I did not receive the OTP',
      'Resend Code': 'Resend Code',
      'Please confirm your\nLicense Information':
      'Please confirm your\nLicense Information',
      'License No': 'License No',
      'License No not be empty!': 'License No not be empty!',
      'Trade Name': 'Trade Name',
      'Trade Name not be empty!': 'Trade Name not be empty!',
      'Scan the back of your\n': 'Scan the back of your\n',
      'Trade License': 'Trade License',
      'WellDone': 'WellDone',
      'Congratulations': 'Congratulations',
      'You have successfully registered\nyour ALGORITHMI account':
      'You have successfully registered\nyour ALGORITHMI account',
      'You have successfully added\nyour':
      'You have successfully added\nyour',
      'You\'re upload file and Submitted\nfor review':
      'You\'re upload file and Submitted\nfor review',
      'Your survey has been Finished and\nSubmitted for review':
      'Your survey has been Finished and\nSubmitted for review',
      'Go to Dashboard': 'Go to Dashboard',
      'Dashboard': 'Dashboard',
      'Wallet': 'Wallet',
      'Settings': 'Settings',
      'Muhammad Usman': 'Muhammad Usman',
      'Verified Account': 'Verified Account',
      'Current location: ': 'Current location: ',
      'Al Barai, Dubai': 'Al Barai, Dubai',
      'Account Type: ': 'Account Type: ',
      'Shop Keeper': 'Shop Keeper',
      'Member Status: ': 'Member Status: ',
      'Bronze': 'Bronze',
      'Questioners: ': 'Questioners: ',
      '3/5 Approved': '3/5 Approved',
      'Questionnaire': 'Questionnaire',
      '1) Is there Storage available.\n2) # of counters.\n3) Sales of tobacco.\n4) Attach image of tobacco shelf.\n5) Ask shop keep top selling brands.\n6) Sales of energy drinks.':
      '1) Is there Storage available.\n2) # of counters.\n3) Sales of tobacco.\n4) Attach image of tobacco shelf.\n5) Ask shop keep top selling brands.\n6) Sales of energy drinks.',
      'Accept': 'Accept',
      'Cancel': 'Cancel',
      'Start New Survey': 'Start New Survey',
      'Last Survey Conducted on 26 Nov 2022':
      'Last Survey Conducted on 26 Nov 2022',
      'Upload Invoices': 'Upload Invoices',
      'Last Invoice Uploaded on 26 Nov 2022':
      'Last Invoice Uploaded on 26 Nov 2022',
      'Upload Stock Report': 'Upload Stock Report',
      'Last Report Uploaded on 26 Nov 2022':
      'Last Report Uploaded on 26 Nov 2022',
      'Let’s Start...': 'Let’s Start...',
      'Quick Supermarket, Majan': 'Quick Supermarket, Majan',
      'Your slot has been blocked for\n60 min':
      'Your slot has been blocked for\n60 min',
      'Start Survey Now!': 'Start Survey Now!',
      'Upload File': 'Upload File',
      'Select File': 'Select File',
      'Question': 'Question',
      'Is there Storage available?':
      'Is there Storage available?',
      'Work on Wholesale activity?': 'Work on Wholesale activity?',
      'How many number of employees?': 'How many number of employees?',
      'Attach image of tobacco shelf.': 'Attach image of tobacco shelf.',
      'Ask shopkeeper top selling brands?':
      'Ask shopkeeper top selling brands?',
      'Take Picture': 'Take Picture',
      'Yes': 'Yes',
      'No': 'No',
      'Select Brand': 'Select Brand',
      'Marlboro': 'Marlboro',
      'Dunhill': 'Dunhill',
      'Pan masala': 'Pan masala',
      'Select Option': 'Select Option',
      'Select Amount': 'Select Amount',
      'Upload Image': 'Upload Image',
      'Sign Out': 'Sign Out',
      'Language': 'Language',
      'Preferences': 'Preferences',
      'Rate the App': 'Rate the App',
      'Help': 'Help',
      'Support': 'Support',
      'Rewards': 'Rewards',
      'You have 568 points': 'You have 568 points',
      'Benefits': 'Benefits',
      'Notifications': 'Notifications',
      'Accounts': 'Accounts',
      'Personal Information': 'Personal Information',
      'Your Account': 'Your Account',
      'Profile': 'Profile',
      'Date Of Birth': 'Date Of Birth',
      'United Arab Emirates': 'United Arab Emirates',
      'Saved Payment Methods': 'Saved Payment Methods',
      'Add New': 'Add New',
      'Add': 'Add',
      'Add Payment Method': 'Add Payment Method',
      'First Abu Dhabi Bank': 'First Abu Dhabi Bank',
      'Dubai Islamic Bank': 'Dubai Islamic Bank',
      'Etisalat Wallet': 'Etisalat Wallet',
      'Magnati': 'Magnati',
      'Bank Account': 'Bank Account',
      'E-Wallet': 'E-Wallet',
      'Today\'s Notification': 'Today\'s Notification',
      'Approved Review': 'Approved Review',
      'Your Given Review about Shop is approved from Admin.':
      'Your Given Review about Shop is approved from Admin.',
      'Send via crypto network': 'Send via crypto network',
      'Send via email/ Phone/ Pay ID': 'Send via email/ Phone/ Pay ID',
      'send to a known crypto address\nvia crypto network':
      'send to a known crypto address\nvia crypto network',
      'Recipient must be a Algorthmi user':
      'Recipient must be a Algorthmi user',
      'Coins': 'Coins',
      'Cash': 'Cash',
      'You currently have': 'You currently have',
      'Link Account': 'Link Account',
      'Transfer to Bank/E-Wallet': 'Transfer to Bank/E-Wallet',
      'Withdraw': 'Withdraw',
      'Transfer': 'Transfer',
      'Withdrawal Money': 'Withdrawal Money',
      'Al Ansari Exchange': 'Al Ansari Exchange',


    },
    'ar_SA': {
      'Select your preferred language': 'اختر لغتك المفضلة',
      'Login': 'تسجيل الدخول',
      'Enter Your Email': 'أدخل بريدك الإلكتروني',
      'Please enter a valid email': 'يرجى إدخال البريد الإلكتروني الصحيح',
      'Enter Your Password': 'ادخل رقمك السري',
      'Password not be empty!': 'كلمة المرور ليست فارغة!',
      'Password must be greater than 5 character!':
      'يجب أن تكون كلمة المرور أكبر من 5 أحرف!',
      'Forgot Password?': 'هل نسيت كلمة السر؟',
      'Forgot Password': 'هل نسيت كلمة السر',
      'Don’t have an account ?   ': 'ليس لديك حساب؟   ',
      'Sign Up': 'اشتراك',
      'Don’t worry! It happens. Please enter the email address associated with your account.':
      'لا تقلق! يحدث ذلك. الرجاء إدخال عنوان البريد الإلكتروني المرتبط بحسابك.',
      'Submit': 'يُقدِّم',
      'Reset Password': 'إعادة تعيين كلمة المرور',
      'Your new password must be different from previous used passwords.':
      'يجب أن تكون كلمة مرورك الجديدة مختلفة عن كلمات المرور السابقة المستخدمة.',
      'Password': 'كلمة المرور',
      'Confirm Password': 'تأكيد كلمة المرور',
      'Select Role': 'حدد الدور',
      'Freelancers': 'لحسابهم الخاص',
      'Shop Owner': 'صاحب محل',
      'Already have an account ?   ': 'هل لديك حساب؟   ',
      'Upload Selfie': 'تحميل صورة شخصية',
      'Take Selfie for starting Questionnaire':
      'التقط صورة شخصية مع ملصق اسم المتجر لبدء الاستبيان',
      'Take Selfie': 'خذ صورة شخصية',
      'Take / Upload': 'خذ / تحميل',
      'Upload from Gallery': 'تحميل من المعرض',
      'Next': 'التالي',
      'Scan Your ID': 'امسح هويتك ضوئيًا',
      'Personal Details\nConfirmation': 'التفاصيل الشخصية \n تأكيد',
      'Mobile & Email\nConfirmation': 'الجوال والبريد\n الإلكتروني التأكيد',
      'Enter Verification\nCode': 'أدخل التحقق \n الرمز',
      'Scan Your License': 'مسح الترخيص\n الخاص بك',
      'License Details\nConfirmation': 'تفاصيل الترخيص \n تأكيد',
      'Confirm': 'يتأكد',
      'Verify': 'يؤكد',
      'Back': 'خلف',
      'Please confirm your\nPersonal Information':
      'الرجاء تأكيد  المعلومات \nالشخصية الخاصة بك',
      'ID Number': 'رقم الهوية',
      'ID Number not be empty!': 'رقم الهوية ليس فارغا!',
      'Full Name': 'الاسم الكامل',
      'Full Name not be empty!': 'الاسم الكامل ليس فارغًا!',
      'Nationality': 'جنسية',
      'Nationality not be empty!': 'الجنسية لا تكون فارغة!',
      'Scan the back of your ': 'امسح الجزء الخلفي من ملف',
      'Emirates ID': 'هويه الإمارات',
      'Start Scanning': 'ابدأ المسح',
      'Card Number': 'رقم البطاقة',
      'Card Number not be empty!': 'رقم البطاقة غير فارغ!',
      'Please Place the back of your\nTrade License inside the frame':
      'الرجاء وضع الجزء الخلفي من\n الرخصة التجارية الخاصة بك داخل الإطار',
      'Scan License': 'رخصة الفحص',
      'Please Place the back of your\nEmirates ID inside the frame':
      'يرجى وضع ظهر بطاقة الهوية \nالإماراتية الخاصة بك داخل الإطار',
      'Scan Card': 'مسح البطاقة',
      'Date of Birth': 'تاريخ الميلاد',
      'Date of Birth not be empty!': 'تاريخ الميلاد يجب ألا يكون فارغًا!',
      'Expiry Date': 'تاريخ الانتهاء',
      'Expiry Date not be empty!':
      'لا يمكن ترك تاريخ انتهاء الصلاحية فارغًا!',
      'Gender': 'جنس',
      'Male': 'ذكر',
      'Female': 'أنثى',
      'Other': 'آخر',
      'Gender not be empty!': 'لا يكون الجنس فارغًا!',
      'Please provide your Mobile Phone Number and Email to continue':
      'يرجى تقديم رقم هاتفك المحمول والبريد الإلكتروني للمتابعة',
      'Phone Number': 'رقم التليفون',
      'Email': 'بريد إلكتروني',
      'Please enter the OTP Code\nwe sent you':
      'الرجاء إدخال رمز OTP \n الذي أرسلناه إليك',
      'I did not receive the OTP': 'لم أحصل على OTP',
      'Resend Code': 'أعد إرسال الرمز',
      'Please confirm your\nLicense Information':
      'الرجاء تأكيد \n معلومات الترخيص الخاصة بك',
      'License No': 'رقم الرخصة',
      'License No not be empty!': 'الرخصة لا لا تكون فارغة!',
      'Trade Name': 'اسم تجاري',
      'Trade Name not be empty!': 'الاسم التجاري يجب ألا يكون فارغًا!',
      'Scan the back of your\n': 'امسح الجزء الخلفي من ملف\n',
      'Trade License': 'الرخصة التجارية',
      'WellDone': 'أحسنت',
      'Congratulations': 'تهانينا',
      'You have successfully registered\nyour ALGORITHMI account':
      'لقد سجلت بنجاح \n حساب ALGORITHMI الخاص بك',
      'You have successfully added\nyour': 'لقد نجحت في إضافة \n الخاص بك',
      'You\'re upload file and Submitted\nfor review':
      'تقوم بتحميل الملف وإرساله \n للمراجعة',
      'Your survey has been Finished and\nSubmitted for review':
      'تم الانتهاء من الاستبيان الخاص بك \n وتم إرساله للمراجعة',
      'Go to Dashboard': 'الذهاب إلى لوحة القيادة',
      'Dashboard': 'لوحة القيادة',
      'Wallet': 'محفظة',
      'Settings': 'جلسة',
      'Muhammad Usman': 'محمد عثمان',
      'Verified Account': 'حساب تم التحقق منه',
      'Current location: ': 'الموقع الحالي: ',
      'Al Barai, Dubai': 'البرعي ، دبي',
      'Account Type: ': 'نوع الحساب: ',
      'Shop Keeper': 'حارس متجر',
      'Member Status: ': 'حالة العضو: ',
      'Bronze': 'برونزية',
      'Questioners: ': 'المستجوبون: ',
      '3/5 Approved': '3/5 معتمد',
      'Questionnaire': 'استبيان',
      '1) Is there Storage available.\n2) # of counters.\n3) Sales of tobacco.\n4) Attach image of tobacco shelf.\n5) Ask shop keep top selling brands.\n6) Sales of energy drinks.':
      '1) هل الموقع به نظام نقاط البيع. \n 2) عدد العدادات. \n 3) بيع التبغ. \n 4) إرفاق صورة لرف التبغ. \n 5) اسأل المتجر عن أفضل العلامات التجارية مبيعًا. \n 6) بيع مشروبات الطاقة.',
      'Accept': 'يقبل',
      'Cancel': 'يلغي',
      'Start New Survey': 'بدء استبيان جديد',
      'Last Survey Conducted on 26 Nov 2022':
      'تم إجراء آخر مسح في 26 نوفمبر 2022',
      'Upload Invoices': 'تحميل الفواتير',
      'Last Invoice Uploaded on 26 Nov 2022':
      'تم تحميل آخر فاتورة في 26 نوفمبر 2022',
      'Upload Stock Report': 'تحميل تقرير المخزون',
      'Last Report Uploaded on 26 Nov 2022':
      'تم تحميل التقرير الأخير في 26 نوفمبر 2022',
      'Let’s Start...': 'لنبدأ...',
      'Quick Supermarket, Majan': 'سوبر ماركت كويك ، مجان',
      'Your slot has been blocked for\n60 min':
      'تم حظر الفتحة الخاصة بك لمدة \n 60 دقيقة',
      'Start Survey Now!': 'ابدأ الاستبيان الآن!',
      'Upload File': 'رفع ملف',
      'Select File': 'حدد ملف',
      'Question': 'سؤال',
      'Is there Storage available?':
      'هل الموقع به نظام نقاط البيع؟',
      'Work on Wholesale activity?': 'العدد الإجمالي للعدادات النقدية؟',
      'How many number of employees?': 'هل يبيعون التبغ؟',
      'Attach image of tobacco shelf.': 'إرفاق صورة رف التبغ.',
      'Ask shopkeeper top selling brands?':
      'اسأل صاحب متجر الماركات الأكثر مبيعًا؟',
      'Take Picture': 'التقط صورة',
      'Yes': 'نعم',
      'No': 'لا',
      'Select Brand': 'اختر الماركة',
      'Marlboro': 'نايك',
      'Dunhill': 'هيرميس',
      'Pan masala': 'لويس فيتون',
      'Select Option': 'حدد خيار',
      'Select Amount': 'حدد المبلغ',
      'Upload Image': 'تحميل الصور',
      'Sign Out': 'خروج',
      'Language': 'لغة',
      'Preferences': 'التفضيلات',
      'Rate the App': 'قيم التطبيق',
      'Help': 'يساعد',
      'Support': 'يدعم',
      'Rewards': 'المكافآت',
      'You have 568 points': 'لديك 568 نقطة',
      'Benefits': 'فوائد',
      'Notifications': 'إشعارات',
      'Accounts': 'حسابات',
      'Personal Information': 'معلومات شخصية',
      'Your Account': 'الحساب الخاص بك',
      'Profile': 'حساب تعريفي',
      'Date Of Birth': 'تاريخ الميلاد',
      'United Arab Emirates': 'الإمارات العربية المتحدة',
      'Saved Payment Methods': 'طرق الدفع المحفوظة',
      'Add New': 'اضف جديد',
      'Add': 'يضيف',
      'Add Payment Method': 'إضافة طريقة دفع',
      'First Abu Dhabi Bank': 'بنك أبوظبي الأول',
      'Dubai Islamic Bank': 'بنك دبي الإسلامي',
      'Etisalat Wallet': 'اتصالات واللي',
      'Magnati': 'ماجناتي',
      'Bank Account': 'حساب البنك',
      'E-Wallet': 'المحفظة الإلكترونية',
      'Today\'s Notification': 'إشعار اليوم',
      'Approved Review': 'مراجعة معتمدة',
      'Your Given Review about Shop is approved from Admin.':
      'تمت الموافقة على مراجعتك المقدمة حول Shop من المسؤول.',
      'Send via crypto network': 'إرسال عبر شبكة التشفير',
      'Send via email/ Phone/ Pay ID': 'إرسال عبر البريد الإلكتروني / الهاتف / معرف الدفع',
      'send to a known crypto address\nvia crypto network':
      'إرسال إلى عنوان تشفير معروف \n عبر شبكة تشفير',
      'Recipient must be a Algorthmi user':
      'يجب أن يكون المستلم من مستخدمي الجورتمي',
      'Coins': 'عملات معدنية',
      'Cash': 'نقدي',
      'You currently have': 'أنت حاليا تملك',
      'Link Account': 'حساب الارتباط',
      'Transfer to Bank/E-Wallet': 'التحويل إلى البنك / المحفظة الإلكترونية',
      'Withdraw': 'ينسحب',
      'Transfer': 'تحويل',
      'Withdrawal Money': 'سحب الأموال',
      'Al Ansari Exchange': 'الانصاري للصرافة',
    },
    'fr_FR': {
      'Select your preferred language':
      'Sélectionnez votre langue préférée',
      'Login': 'Connexion',
      'Enter Your Email': 'Entrer votre Email',
      'Please enter a valid email': 'veuillez entrer un email valide',
      'Enter Your Password': 'Tapez votre mot de passe',
      'Password not be empty!': 'Le mot de passe ne doit pas être vide !',
      'Password must be greater than 5 character!':
      'Le mot de passe doit comporter plus de 5 caractères!',
      'Forgot Password?': 'Mot de passe oublié?',
      'Forgot Password': 'Mot de passe oublié',
      'Don’t have an account ?   ': 'Vous n\'avez pas de compte ?   ',
      'Sign Up': 'S\'inscrire',
      'Don’t worry! It happens. Please enter the email address associated with your account.':
      'Ne t\'inquiète pas! Ça arrive. Veuillez saisir l\'adresse e-mail associée à votre compte.',
      'Submit': 'Soumettre',
      'Reset Password': 'Réinitialiser le mot de passe',
      'Your new password must be different from previous used passwords.':
      'Votre nouveau mot de passe doit être différent des mots de passe utilisés précédemment.',
      'Password': 'mot de passe',
      'Confirm Password': 'Confirmez le mot de passe',
      'Select Role': 'Sélectionnez un rôle',
      'Freelancers': 'Pigistes',
      'Shop Owner': 'Propriétaire de la boutique',
      'Already have an account ?   ': 'Vous avez déjà un compte?   ',
      'Upload Selfie': 'Télécharger un selfie',
      'Take Selfie for starting Questionnaire':
      'Prenez Selfie avec l\'étiquette du nom de la boutique pour commencer le questionnaire',
      'Take Selfie': 'Prendre un selfie',
      'Take / Upload': 'Prendre / Télécharger',
      'Upload from Gallery': 'Télécharger depuis la galerie',
      'Next': 'Suivant',
      'Scan Your ID': 'Scannez votre pièce d\'identité',
      'Personal Details\nConfirmation': 'Détails personnels\nConfirmation',
      'Mobile & Email\nConfirmation': 'Mobile et e-mail\nConfirmation',
      'Enter Verification\nCode': 'Entrez le code\nde vérification',
      'Scan Your License': 'Scannez votre \nlicence',
      'License Details\nConfirmation':
      'Détails de la licence\nConfirmation',
      'Confirm': 'Confirmer',
      'Verify': 'Vérifier',
      'Back': 'Dos',
      'Please confirm your\nPersonal Information':
      'Veuillez confirmer vos \n informations personnelles',
      'ID Number': 'Numéro d\'identification',
      'ID Number not be empty!':
      'Le numéro d\'identification ne doit pas être vide!',
      'Full Name': 'Nom et prénom',
      'Full Name not be empty!': 'Le nom complet n\'est pas vide!',
      'Nationality': 'Nationalité',
      'Nationality not be empty!': 'La nationalité ne doit pas être vide!',
      'Scan the back of your ': 'Scannez le dos de votre ',
      'Emirates ID': 'carte d\'identité Emirates',
      'Start Scanning': 'Lancer la numérisation',
      'Card Number': 'Numéro de carte',
      'Card Number not be empty!':
      'Le numéro de carte ne doit pas être vide!',
      'Please Place the back of your\nTrade License inside the frame':
      'Veuillez placer le dos de \nvotre licence commerciale à l\'intérieur du cadre',
      'Scan License': 'Licence de numérisation',
      'Please Place the back of your\nEmirates ID inside the frame':
      'Veuillez placer le dos de votre carte \nd\'identité Emirates à l\'intérieur du cadre',
      'Scan Card': 'Numériser la carte',
      'Date of Birth': 'Date de naissance',
      'Date of Birth not be empty!':
      'La date de naissance n\'est pas vide!',
      'Expiry Date': 'Date d\'expiration',
      'Expiry Date not be empty!': 'La date d\'expiration n\'est pas vide!',
      'Gender': 'Genre',
      'Male': 'Homme',
      'Female': 'Femme',
      'Other': 'Autre',
      'Gender not be empty!': 'Le genre n\'est pas vide !',
      'Please provide your Mobile Phone Number and Email to continue':
      'Veuillez fournir votre numéro de téléphone portable et votre e-mail pour continuer',
      'Phone Number': 'Numéro de téléphone',
      'Email': 'E-mail',
      'Please enter the OTP Code\nwe sent you':
      'Veuillez entrer le code OTP\nque nous vous avons envoyé',
      'I did not receive the OTP': 'Je n\'ai pas reçu l\'OTP',
      'Resend Code': 'Renvoyer le code',
      'Please confirm your\nLicense Information':
      'Veuillez confirmer vos\ninformations de licence',
      'License No': 'License No',
      'License No not be empty!': 'N ° de licence',
      'Trade Name': 'Trade Name',
      'Trade Name not be empty!': 'Licence Non pas être vide !',
      'Scan the back of your\n': 'Nom commercial\n',
      'Trade License': 'Le nom commercial ne doit pas être vide!',
      'WellDone': 'Bien joué',
      'Congratulations': 'Toutes nos félicitations',
      'You have successfully registered\nyour ALGORITHMI account':
      'Vous avez enregistré avec succès \n votre compte ALGORITHM',
      'You have successfully added\nyour':
      'Vous avez ajouté avec succès \n votre',
      'You\'re upload file and Submitted\nfor review':
      'Vous téléchargez le fichier et l\'envoyez \n pour examen',
      'Your survey has been Finished and\nSubmitted for review':
      'Votre enquête a été terminée et \n soumise pour examen',
      'Go to Dashboard': 'Aller au tableau de bord',
      'Dashboard': 'Tableau de bord',
      'Wallet': 'Portefeuille',
      'Settings': 'Paramètre',
      'Muhammad Usman': 'Mohammed Ousman',
      'Verified Account': 'Compte vérifié',
      'Current location: ': 'Localisation actuelle: ',
      'Al Barai, Dubai': 'Al Baraï, Dubaï',
      'Account Type: ': 'Type de compte: ',
      'Shop Keeper': 'Magasinier',
      'Member Status: ': 'Statut de membre : ',
      'Bronze': 'Bronze',
      'Questioners: ': 'Interrogateurs : ',
      '3/5 Approved': '3/5 Approuvé',
      'Questionnaire': 'Questionnaire',
      '1) Is there Storage available.\n2) # of counters.\n3) Sales of tobacco.\n4) Attach image of tobacco shelf.\n5) Ask shop keep top selling brands.\n6) Sales of energy drinks.':
      '1) L\'emplacement dispose-t-il d\'un système de point de vente. \n 2) # de compteurs. \n 3) Ventes de tabac. \n 4) Joignez l\'image de l\'étagère à tabac. \n 5) Demandez au magasin de conserver les marques les plus vendues. \n 6) Ventes de boissons énergisantes.',
      'Accept': 'Accepter',
      'Cancel': 'Annuler',
      'Start New Survey': 'Commencer une nouvelle enquête',
      'Last Survey Conducted on 26 Nov 2022':
      'Dernière enquête réalisée le 26 novembre 2022',
      'Upload Invoices': 'Télécharger des factures',
      'Last Invoice Uploaded on 26 Nov 2022':
      'Dernière facture téléchargée le 26 novembre 2022',
      'Upload Stock Report': 'Télécharger le rapport de stock',
      'Last Report Uploaded on 26 Nov 2022':
      'Dernier rapport mis en ligne le 26 nov. 2022',
      'Let’s Start...': 'Commençons...',
      'Quick Supermarket, Majan': 'Supermarché rapide, Majan',
      'Your slot has been blocked for\n60 min':
      'Votre emplacement a été bloqué pendant \n60 min',
      'Start Survey Now!': 'Commencez l\'enquête maintenant!',
      'Upload File': 'Téléverser un fichier',
      'Select File': 'Choisir le dossier',
      'Question': 'Question',
      'Is there Storage available?':
      'L\'emplacement dispose-t-il d\'un système de point de vente?',
      'Work on Wholesale activity?': 'Nombre total de guichets?',
      'How many number of employees?': 'Vendent-ils du tabac ?',
      'Attach image of tobacco shelf.':
      'Joindre l\'image de l\'étagère à tabac.',
      'Ask shopkeeper top selling brands?':
      'Demandez aux commerçants les marques les plus vendues?',
      'Take Picture': 'Prendre une photo',
      'Yes': 'Oui',
      'No': 'Non',
      'Select Brand': 'Sélectionner la marque',
      'Marlboro': 'Marlboro',
      'Dunhill': 'Dunhill',
      'Pan masala': 'Pan masala',
      'Select Option': 'Sélectionner une option',
      'Select Amount': 'Sélectionnez le montant',
      'Upload Image': 'Télécharger une image',
      'Sign Out': 'Se déconnecter',
      'Language': 'Langue',
      'Preferences': 'Préférences',
      'Rate the App': 'Évaluer l\'application',
      'Help': 'Aider',
      'Support': 'Soutien',
      'Rewards': 'Récompenses',
      'You have 568 points': 'Vous avez 568 points',
      'Benefits': 'Avantages',
      'Notifications': 'Avis',
      'Accounts': 'Comptes',
      'Personal Information': 'Informations personnelles',
      'Your Account': 'Votre compte',
      'Profile': 'Profil',
      'Date Of Birth': 'Date de naissance',
      'United Arab Emirates': 'Emirats Arabes Unis',
      'Saved Payment Methods': 'Méthodes de paiement enregistrées',
      'Add New': 'Ajouter nouveau',
      'Add': 'Ajouter',
      'Add Payment Method': 'Ajouter un mode de paiement',
      'First Abu Dhabi Bank': 'Première banque d\'Abu Dhabi',
      'Dubai Islamic Bank': 'Banque islamique de Dubaï',
      'Etisalat Wallet': 'Étisalat Walle',
      'Magnati': 'Magnati',
      'Bank Account': 'Compte bancaire',
      'E-Wallet': 'Portefeuille électronique',
      'Today\'s Notification': 'Notification d\'aujourd\'hui',
      'Approved Review': 'Examen approuvé',
      'Your Given Review about Shop is approved from Admin.':
      'Votre avis sur la boutique est approuvé par l\'administrateur.',
      'Send via crypto network': 'Envoyer via le réseau crypto',
      'Send via email/ Phone/ Pay ID': 'Envoyer par e-mail/Téléphone/Pay ID',
      'send to a known crypto address\nvia crypto network':
      'envoyer à une adresse crypto connue \n via un réseau crypto',
      'Recipient must be a Algorthmi user':
      'Le destinataire doit être un utilisateur d\'Algorthmi',
      'Coins': 'Pièces de monnaie',
      'Cash': 'Espèces',
      'You currently have': 'Tu as présentement',
      'Link Account': 'Lien de compte',
      'Transfer to Bank/E-Wallet': 'Virement bancaire / portefeuille électronique',
      'Withdraw': 'Retirer',
      'Transfer': 'Transfert',
      'Withdrawal Money': 'Retrait d\'argent',
      'Al Ansari Exchange': 'Échange Al Ansari',
    },
    'hi_IN': {
      'Select your preferred language': 'अपनी पसंदीदा भाषा का चयन करें',
      'Login': 'लॉग इन करें',
      'Enter Your Email': 'अपना ईमेल दर्ज करें',
      'Please enter a valid email': 'कृपया एक मान्य ईमेल दर्ज करें',
      'Enter Your Password': 'अपना कूटशब्द भरें',
      'Password not be empty!': 'पासवर्ड खाली न हो!',
      'Password must be greater than 5 character!':
      'पासवर्ड 5 कैरेक्टर से बड़ा होना चाहिए!',
      'Forgot Password?': 'पासवर्ड भूल गए?',
      'Forgot Password': 'पासवर्ड भूल गए',
      'Don’t have an account ?   ': 'खाता नहीं है?   ',
      'Sign Up': 'साइन अप करें',
      'Don’t worry! It happens. Please enter the email address associated with your account.':
      'चिंता मत करो! ऐसा होता है। कृपया अपने खाते से संबद्ध ईमेल पता दर्ज करें।',
      'Submit': 'जमा करना',
      'Reset Password': 'पासवर्ड रीसेट',
      'Your new password must be different from previous used passwords.':
      'आपका नया पासवर्ड पिछले इस्तेमाल किए गए पासवर्ड से अलग होना चाहिए।',
      'Password': 'पासवर्ड',
      'Confirm Password': 'पासवर्ड की पुष्टि कीजिये',
      'Select Role': 'भूमिका का चयन करें',
      'Freelancers': 'स्वतंत्र',
      'Shop Owner': 'दुकान का मालिक',
      'Already have an account ?   ':
      'क्या आपके पास पहले से एक खाता मौजूद है?   ',
      'Upload Selfie': 'सेल्फी अपलोड करें',
      'Take Selfie for starting Questionnaire':
      'प्रश्नावली शुरू करने के लिए दुकान के नाम के लेबल के साथ सेल्फी लें',
      'Take Selfie': 'सेल्फी लो',
      'Take / Upload': 'लो / अपलोड करो',
      'Upload from Gallery': 'गैलरी से अपलोड करें',
      'Next': 'अगला',
      'Scan Your ID': 'अपनी आईडी स्कैन करें',
      'Personal Details\nConfirmation': 'व्यक्तिगत विवरण\nपुष्टि',
      'Mobile & Email\nConfirmation': 'मोबाइल और ईमेल\nपुष्टि',
      'Enter Verification\nCode': 'सत्यापन\nकोड दर्ज करें',
      'Scan Your License': 'अपना लाइसेंस \nस्कैन करें',
      'License Details\nConfirmation': 'लाइसेंस विवरण\nपुष्टि',
      'Confirm': 'पुष्टि करना',
      'Verify': 'सत्यापित करना',
      'Back': 'पीछे',
      'Please confirm your\nPersonal Information':
      'कृपया अपनी \n व्यक्तिगत जानकारी की पुष्टि करेंं',
      'ID Number': 'आईडी नंबर',
      'ID Number not be empty!': 'आईडी नंबर खाली न हो!',
      'Full Name': 'पूरा नाम',
      'Full Name not be empty!': 'पूरा नाम खाली नहीं है!',
      'Nationality': 'राष्ट्रीयता',
      'Nationality not be empty!': 'राष्ट्रीयता खाली नहीं!',
      'Scan the back of your ': 'अपने पीछे स्कैन करें ',
      'Emirates ID': 'अमीरात आईडी',
      'Start Scanning': 'स्कैन करना प्रारंभ करें',
      'Card Number': 'कार्ड संख्या',
      'Card Number not be empty!': 'कार्ड नंबर खाली न हो!',
      'Please Place the back of your\nTrade License inside the frame':
      'कृपया अपने ट्रेड लाइसेंस के \nपिछले हिस्से को फ्रेम के अंदर रखें',
      'Scan License': 'स्कैन लाइसेंस',
      'Please Place the back of your\nEmirates ID inside the frame':
      'कृपया अपनी अमीरात आईडी के \nपिछले हिस्से को फ्रेम के अंदर रखें',
      'Scan Card': 'स्कैन कार्ड',
      'Date of Birth': 'जन्म की तारीख',
      'Date of Birth not be empty!': 'जन्मतिथि खाली नहीं है!',
      'Expiry Date': 'समाप्ति तिथि',
      'Expiry Date not be empty!': 'समाप्ति तिथि खाली नहीं है!',
      'Gender': 'लिंग',
      'Male': 'नर',
      'Female': 'महिला',
      'Other': 'अन्य',
      'Gender not be empty!': 'लिंग खाली नहीं है!',
      'Please provide your Mobile Phone Number and Email to continue':
      'जारी रखने के लिए कृपया अपना मोबाइल फ़ोन नंबर और ईमेल प्रदान करें',
      'Phone Number': 'फ़ोन नंबर',
      'Email': 'ईमेल',
      'Please enter the OTP Code\nwe sent you':
      'कृपया ओटीपी कोड दर्ज करें\nहमने आपको भेजा है',
      'I did not receive the OTP': 'मुझे ओटीपी प्राप्त नहीं हुआ',
      'Resend Code': 'पुन: कोड भेजे',
      'Please confirm your\nLicense Information':
      'कृपया अपनी \nलाइसेंस जानकारी की पुष्टि करें',
      'License No': 'अनुज्ञापत्र क्रमांक',
      'License No not be empty!': 'लाइसेंस नहीं खाली नहीं!',
      'Trade Name': 'Trade Name',
      'Trade Name not be empty!': 'व्यापरिक नाम',
      'Scan the back of your\n': 'ट्रेड नाम खाली न हो!\n',
      'Trade License': 'अपने पीछे स्कैन करें',
      'WellDone': 'बहुत अच्छा',
      'Congratulations': 'बधाई हो',
      'You have successfully registered\nyour ALGORITHMI account':
      'आपने \n अपना ALGORITHMI खाता सफलतापूर्वक पंजीकृत कर लिया है',
      'You have successfully added\nyour':
      'आपने \n सफलतापूर्वक जोड़ लिया है',
      'You\'re upload file and Submitted\nfor review':
      'आप फ़ाइल अपलोड कर रहे हैं और \n समीक्षा के लिए सबमिट कर दिया गया है',
      'Your survey has been Finished and\nSubmitted for review':
      'आपका सर्वे पूरा हो चुका है और \n समीक्षा के लिए सबमिट कर दिया गया है',
      'Go to Dashboard': 'डैशबोर्ड पर जाएँ',
      'Dashboard': 'डैशबोर्ड',
      'Wallet': 'बटुआ',
      'Settings': 'सेटिंग',
      'Muhammad Usman': 'मुहम्मद उस्मान',
      'Verified Account': 'सत्यापित खाते',
      'Current location: ': 'वर्तमान स्थान: ',
      'Al Barai, Dubai': 'अल बरई, दुबई',
      'Account Type: ': 'खाते का प्रकार: ',
      'Shop Keeper': 'दुकानदारr',
      'Member Status: ': 'सदस्य स्थिति: ',
      'Bronze': 'पीतल',
      'Questioners: ': 'प्रश्नकर्ता: ',
      '3/5 Approved': '3/5 स्वीकृत',
      'Questionnaire': 'प्रश्नावली',
      '1) Is there Storage available.\n2) # of counters.\n3) Sales of tobacco.\n4) Attach image of tobacco shelf.\n5) Ask shop keep top selling brands.\n6) Sales of energy drinks.':
      '1) क्या स्थान में पीओएस सिस्टम है। \n 2) # काउंटरों की। \n 3) तंबाकू की बिक्री। \n 4) तंबाकू शेल्फ की तस्वीर अटैच करें। \n 5) शॉप कीप टॉप सेलिंग ब्रांड्स से पूछें। \n 6) ऊर्जा पेय की बिक्री।',
      'Accept': 'स्वीकार करना',
      'Cancel': 'रद्द करना',
      'Start New Survey': 'नया सर्वेक्षण शुरू करें',
      'Last Survey Conducted on 26 Nov 2022':
      'अंतिम सर्वेक्षण 26 नवंबर 2022 को आयोजित किया गया',
      'Upload Invoices': 'चालान अपलोड करें',
      'Last Invoice Uploaded on 26 Nov 2022':
      'अंतिम चालान 26 नवंबर 2022 को अपलोड किया गया',
      'Upload Stock Report': 'स्टॉक रिपोर्ट अपलोड करें',
      'Last Report Uploaded on 26 Nov 2022':
      'अंतिम रिपोर्ट 26 नवंबर 2022 को अपलोड की गई',
      'Let’s Start...': 'चलो शुरू करो...',
      'Quick Supermarket, Majan': 'क्विक सुपरमार्केट, माजन',
      'Your slot has been blocked for\n60 min':
      'आपका स्लॉट \n60 मिनट के लिए ब्लॉक कर दिया गया है',
      'Start Survey Now!': 'अभी सर्वेक्षण शुरू करें!',
      'Upload File': 'फ़ाइल अपलोड करें',
      'Select File': 'फ़ाइल का चयन करें',
      'Question': 'सवाल',
      'Is there Storage available?':
      'क्या स्थान में पीओएस सिस्टम है?',
      'Work on Wholesale activity?': 'कैश काउंटरों की कुल संख्या?',
      'How many number of employees?': 'क्या वे तंबाकू बेचते हैं?',
      'Attach image of tobacco shelf.': 'तंबाकू शेल्फ की छवि संलग्न करें।',
      'Ask shopkeeper top selling brands?':
      'दुकानदार से पूछें सबसे ज्यादा बिकने वाले ब्रांड?',
      'Take Picture': 'तस्वीर ले लो',
      'Yes': 'हाँ',
      'No': 'नहीं',
      'Select Brand': 'ब्रांड का चयन करें',
      'Marlboro': 'नाइके',
      'Dunhill': 'हेमीज़',
      'Pan masala': 'लुई वुइटन',
      'Select Option': 'विकल्प चुनें',
      'Select Amount': 'राशि का चयन करें',
      'Upload Image': 'तस्विर अपलोड करना',
      'Sign Out': 'साइन आउट',
      'Language': 'भाषा',
      'Preferences': 'पसंद',
      'Rate the App': 'एप्लिकेशन की श्रेणी बताओ',
      'Help': 'मदद',
      'Support': 'सहायता',
      'Rewards': 'पुरस्कार',
      'You have 568 points': 'आपके 568 अंक हैं',
      'Benefits': 'फ़ायदे',
      'Notifications': 'सूचनाएं',
      'Accounts': 'हिसाब किताब',
      'Personal Information': 'व्यक्तिगत जानकारी',
      'Your Account': 'आपका खाता',
      'Profile': 'प्रोफ़ाइल',
      'Date Of Birth': 'जन्म की तारीख',
      'United Arab Emirates': 'संयुक्त अरब अमीरातs',
      'Saved Payment Methods': 'सहेजे गए भुगतान के तरीके',
      'Add New': 'नया जोड़ो',
      'Add': 'जोड़ना',
      'Add Payment Method': 'भुगतान विधि जोड़ें',
      'First Abu Dhabi Bank': 'पहला अबू धाबी बैंक',
      'Dubai Islamic Bank': 'दुबई इस्लामिक बैंक',
      'Etisalat Wallet': 'एतिसलात वाले',
      'Magnati': 'मैग्नेटी',
      'Bank Account': 'बैंक खाता',
      'E-Wallet': 'ई-बटुआ',
      'Today\'s Notification': 'आज की अधिसूचना',
      'Approved Review': 'स्वीकृत समीक्षा',
      'Your Given Review about Shop is approved from Admin.':
      'शॉप के बारे में आपकी दी गई समीक्षा एडमिन से स्वीकृत है।',
      'Send via crypto network': 'क्रिप्टो नेटवर्क के माध्यम से भेजें',
      'Send via email/ Phone/ Pay ID': 'ईमेल/फोन/पे आईडी द्वारा भेजें',
      'send to a known crypto address\nvia crypto network':
      'ज्ञात क्रिप्टो पते \n पर क्रिप्टो नेटवर्क के माध्यम से भेजें',
      'Recipient must be a Algorthmi user':
      'प्राप्तकर्ता एक Algorthmi उपयोगकर्ता होना चाहिए',
      'Coins': 'सिक्के',
      'Cash': 'नकद',
      'You currently have': 'इस समय आपके पास',
      'Link Account': 'खाते लिंक करें',
      'Transfer to Bank/E-Wallet': 'बैंक / ई-वॉलेट में स्थानांतरण',
      'Withdraw': 'निकालना',
      'Transfer': 'स्थानांतरण',
      'Withdrawal Money': 'निकासी धन',
      'Al Ansari Exchange': 'अल अंसारी एक्सचेंज',
    },
    'ml_IN': {
      'Select your preferred language':
      'നിങ്ങൾ ഇഷ്ടപ്പെടുന്ന ഭാഷ തിരഞ്ഞെടുക്കുക',
      'Login': 'ലോഗിൻ',
      'Enter Your Email': 'നിങ്ങളുടെ ഇമെയിൽ നൽകുക',
      'Please enter a valid email': 'സാധുവായ ഒരു ഇമെയിൽ നൽകുക',
      'Enter Your Password': 'നിങ്ങളുടെ പാസ്‌വേഡ് നൽകുക',
      'Password not be empty!': 'പാസ്‌വേഡ് ശൂന്യമായിരിക്കരുത്!',
      'Password must be greater than 5 character!':
      'പാസ്‌വേഡ് 5 പ്രതീകത്തിൽ കൂടുതലായിരിക്കണം!',
      'Forgot Password?': 'പാസ്വേഡ് മറന്നോ?',
      'Forgot Password': 'പാസ്വേഡ് മറന്നോ',
      'Don’t have an account ?   ': 'ഒരു അക്കൗണ്ട് ഇല്ലേ?   ',
      'Sign Up': 'സൈൻ അപ്പ് ചെയ്യുക',
      'Don’t worry! It happens. Please enter the email address associated with your account.':
      'വിഷമിക്കേണ്ട! അത് സംഭവിക്കുന്നു. നിങ്ങളുടെ അക്കൗണ്ടുമായി ബന്ധപ്പെട്ട ഇമെയിൽ വിലാസം ദയവായി നൽകുക.',
      'Submit': 'സമർപ്പിക്കുക',
      'Reset Password': 'പാസ്‌വേഡ് \nപുനഃസജ്ജമാക്കുക',
      'Your new password must be different from previous used passwords.':
      'നിങ്ങളുടെ പുതിയ പാസ്‌വേഡ് മുമ്പ് ഉപയോഗിച്ച പാസ്‌വേഡുകളിൽ നിന്ന് വ്യത്യസ്തമായിരിക്കണം.',
      'Password': 'പാസ്വേഡുകൾ',
      'Confirm Password': 'പാസ്വേഡ് സ്ഥിരീകരിക്കുക',
      'Select Role': 'റോൾ തിരഞ്ഞെടുക്കുക',
      'Freelancers': 'ഫ്രീലാൻസർമാർ',
      'Shop Owner': 'കട ഉടമ',
      'Already have an account ?   ': 'ഇതിനകം ഒരു അക്കൗണ്ട് ഉണ്ടോ?   ',
      'Upload Selfie': 'സെൽഫി അപ്‌ലോഡ്\nചെയ്യുക',
      'Take Selfie for starting Questionnaire':
      'ചോദ്യാവലി ആരംഭിക്കുന്നതിന് ഷോപ്പിന്റെ പേര് ലേബൽ സഹിതം സെൽഫി എടുക്കുക',
      'Take Selfie': 'സെൽഫി എടുക്കുക',
      'Take / Upload': 'എടുക്കുക / അപ്‌ലോഡ് ചെയ്യുക',
      'Upload from Gallery': 'ഗാലറിയിൽ നിന്ന് അപ്‌ലോഡ് ചെയ്യുക',
      'Next': 'അടുത്തത്',
      'Scan Your ID': 'നിങ്ങളുടെ ഐഡി \nസ്കാൻ ചെയ്യുക',
      'Personal Details\nConfirmation': 'വ്യക്തിഗത വിശദാംശങ്ങൾ സ്ഥിരീകരണം',
      'Mobile & Email\nConfirmation': 'മൊബൈലും ഇമെയിലും\nസ്ഥിരീകരണം',
      'Enter Verification\nCode': 'പരിശോധിച്ചുറപ്പിക്കൽ\nകോഡ് നൽകുക',
      'Scan Your License': 'നിങ്ങളുടെ ലൈസൻസ് \nസ്കാൻ ചെയ്യുക',
      'License Details\nConfirmation': 'ലൈസൻസ് വിശദാംശങ്ങൾ\nസ്ഥിരീകരണം',
      'Confirm': 'സ്ഥിരീകരിക്കുക',
      'Verify': 'സ്ഥിരീകരിക്കുക',
      'Back': 'തിരികെ',
      'Please confirm your\nPersonal Information':
      'നിങ്ങളുടെ വ്യക്തിഗത \nവിവരങ്ങൾ സ്ഥിരീകരിക്കുക',
      'ID Number': 'ഐഡി നമ്പർ',
      'ID Number not be empty!': 'ഐഡി നമ്പർ ശൂന്യമായിരിക്കരുത്!',
      'Full Name': 'പൂർണ്ണമായ പേര്',
      'Full Name not be empty!': 'മുഴുവൻ പേര് ശൂന്യമല്ല!',
      'Nationality': 'ദേശീയത',
      'Nationality not be empty!': 'ദേശീയത ശൂന്യമാകരുത്!',
      'Scan the back of your ': 'നിങ്ങളുടെ പിൻഭാഗം സ്കാൻ ചെയ്യുക ',
      'Emirates ID': 'എമിറേറ്റ്സ് ഐഡി',
      'Start Scanning': 'സ്കാനിംഗ് ആരംഭിക്കുക',
      'Card Number': 'കാർഡ് നമ്പർ',
      'Card Number not be empty!': 'കാർഡ് നമ്പർ ശൂന്യമായിരിക്കരുത്!',
      'Please Place the back of your\nTrade License inside the frame':
      'നിങ്ങളുടെ ട്രേഡ് ലൈസൻസിന്റെ \nപിൻഭാഗം ഫ്രെയിമിനുള്ളിൽ വയ്ക്കുക',
      'Scan License': 'സ്കാൻ ലൈസൻസ്',
      'Please Place the back of your\nEmirates ID inside the frame':
      'നിങ്ങളുടെ എമിറേറ്റ്സ് ഐഡിയുടെ \nപിൻഭാഗം ഫ്രെയിമിനുള്ളിൽ വയ്ക്കുക',
      'Scan Card': 'കാർഡ് സ്കാൻ ചെയ്യുക',
      'Date of Birth': 'ജനനത്തീയതി',
      'Date of Birth not be empty!': 'ജനനത്തീയതി ശൂന്യമല്ല!',
      'Expiry Date': 'കാലഹരണപ്പെടുന്ന തീയതി',
      'Expiry Date not be empty!': 'കാലഹരണ തീയതി ശൂന്യമല്ല!',
      'Gender': 'ലിംഗഭേദം',
      'Male': 'ആൺ',
      'Female': 'സ്ത്രീ',
      'Other': 'മറ്റുള്ളവ',
      'Gender not be empty!': 'ലിംഗഭേദം ശൂന്യമല്ല!',
      'Please provide your Mobile Phone Number and Email to continue':
      'തുടരാൻ നിങ്ങളുടെ മൊബൈൽ ഫോൺ നമ്പറും ഇമെയിലും നൽകുക',
      'Phone Number': 'ഫോൺ നമ്പർ',
      'Email': 'ഇമെയിൽ',
      'Please enter the OTP Code\nwe sent you':
      'ദയവായി OTP കോഡ് നൽകുക\nഞങ്ങൾ നിങ്ങൾക്ക് അയച്ചു',
      'I did not receive the OTP': 'എനിക്ക് OTP ലഭിച്ചില്ല',
      'Resend Code': 'കോഡ് വീണ്ടും അയക്കുക',
      'Please confirm your\nLicense Information':
      'നിങ്ങളുടെ \nലൈസൻസ് വിവരങ്ങൾ സ്ഥിരീകരിക്കുക',
      'License No': 'ലൈസൻസ് നമ്പർ',
      'License No not be empty!': 'ലൈസൻസ് നമ്പർ ശൂന്യമാകരുത്!',
      'Trade Name': 'വ്യാപാര നാമം',
      'Trade Name not be empty!': 'വ്യാപാര നാമം ശൂന്യമായിരിക്കരുത്!',
      'Scan the back of your\n': 'നിങ്ങളുടെ പിൻഭാഗം സ്കാൻ ചെയ്യുക\n',
      'Trade License': 'വ്യാപാര ലൈസൻസ്',
      'WellDone': 'നന്നായി ചെയ്തു',
      'Congratulations': 'അഭിനന്ദനങ്ങൾ',
      'You have successfully registered\nyour ALGORITHMI account':
      'നിങ്ങളുടെ ALGORITHMI അക്കൗണ്ട് \n നിങ്ങൾ വിജയകരമായി രജിസ്റ്റർ ചെയ്തു',
      'You have successfully added\nyour': 'നിങ്ങൾ \n നിങ്ങളുടെ',
      'You\'re upload file and Submitted\nfor review':
      'നിങ്ങൾ ഫയൽ അപ്‌ലോഡ് ചെയ്യുകയും \n അവലോകനത്തിനായി സമർപ്പിക്കുകയും ചെയ്തു',
      'Your survey has been Finished and\nSubmitted for review':
      'നിങ്ങളുടെ സർവേ പൂർത്തിയായി \n അവലോകനത്തിനായി സമർപ്പിച്ചു',
      'Go to Dashboard': 'ഡാഷ്‌ബോർഡിലേക്ക് പോകുക',
      'Dashboard': 'ഡാഷ്ബോർഡ്',
      'Wallet': 'വാലറ്റ്',
      'Settings': 'ക്രമീകരണം',
      'Muhammad Usman': 'മുഹമ്മദ് ഉസ്മാൻ',
      'Verified Account': 'സ്ഥിരീകരിച്ച അക്കൗണ്ട്',
      'Current location: ': 'ഇപ്പോഴുള്ള സ്ഥലം: ',
      'Al Barai, Dubai': 'അൽ ബറായ്, ദുബായ്',
      'Account Type: ': 'അക്കൗണ്ട് തരം: ',
      'Shop Keeper': 'ഷോപ്പ് കീപ്പർ',
      'Member Status: ': 'അംഗ നില: ',
      'Bronze': 'വെങ്കലം',
      'Questioners: ': 'ചോദ്യകർത്താക്കൾ: ',
      '3/5 Approved': '3/5 അംഗീകരിച്ചു',
      'Questionnaire': 'ചോദ്യാവലി',
      '1) Is there Storage available.\n2) # of counters.\n3) Sales of tobacco.\n4) Attach image of tobacco shelf.\n5) Ask shop keep top selling brands.\n6) Sales of energy drinks.':
      '1) ലൊക്കേഷനിൽ POS സിസ്റ്റം ഉണ്ടോ. \n 2) # കൗണ്ടറുകൾ. \n 3) പുകയില വിൽപ്പന. \n 4) പുകയില ഷെൽഫിന്റെ ചിത്രം അറ്റാച്ചുചെയ്യുക. \n 5) ഏറ്റവും കൂടുതൽ വിറ്റഴിക്കപ്പെടുന്ന ബ്രാൻഡുകൾ സൂക്ഷിക്കാൻ ഷോപ്പിനോട് ആവശ്യപ്പെടുക. \n 6) ഊർജ്ജ പാനീയങ്ങളുടെ വിൽപ്പന.',
      'Accept': 'സ്വീകരിക്കുക',
      'Cancel': 'റദ്ദാക്കുക',
      'Start New Survey': 'പുതിയ സർവേ ആരംഭിക്കുക',
      'Last Survey Conducted on 26 Nov 2022':
      '2022 നവംബർ 26-നാണ് അവസാനമായി സർവേ നടത്തിയത്',
      'Upload Invoices': 'ഇൻവോയ്‌സുകൾ \nഅപ്‌ലോഡ് ചെയ്യുക',
      'Last Invoice Uploaded on 26 Nov 2022':
      '2022 നവംബർ 26-നാണ് അവസാനമായി ഇൻവോയ്സ് അപ്‌ലോഡ് ചെയ്തത്',
      'Upload Stock Report': 'സ്റ്റോക്ക് റിപ്പോർട്ട് \nഅപ്ലോഡ് ചെയ്യുക',
      'Last Report Uploaded on 26 Nov 2022':
      '2022 നവംബർ 26-നാണ് അവസാനമായി റിപ്പോർട്ട് അപ്‌ലോഡ് ചെയ്തത്',
      'Let’s Start...': 'നമുക്ക് തുടങ്ങാം...',
      'Quick Supermarket, Majan': 'ദ്രുത സൂപ്പർമാർക്കറ്റ്, മജൻ',
      'Your slot has been blocked for\n60 min':
      'നിങ്ങളുടെ സ്ലോട്ട് \n60 മിനിറ്റായി തടഞ്ഞിരിക്കുന്നു',
      'Start Survey Now!': 'ഇപ്പോൾ സർവേ ആരംഭിക്കുക!',
      'Upload File': 'ഫയൽ അപ്‌ലോഡ് ചെയ്യുക',
      'Select File': 'ഫയൽ തിരഞ്ഞെടുക്കുക',
      'Question': 'ചോദ്യം',
      'Is there Storage available?':
      'ലൊക്കേഷനിൽ POS സിസ്റ്റം ഉണ്ടോ?',
      'Work on Wholesale activity?': 'ക്യാഷ് കൗണ്ടറുകളുടെ ആകെ എണ്ണം?',
      'How many number of employees?': 'അവർ പുകയില വിൽക്കുന്നുണ്ടോ?',
      'Attach image of tobacco shelf.':
      'പുകയില ഷെൽഫിന്റെ ചിത്രം അറ്റാച്ചുചെയ്യുക.',
      'Ask shopkeeper top selling brands?':
      'ഏറ്റവും കൂടുതൽ വിൽക്കുന്ന ബ്രാൻഡുകൾ കടയുടമയോട് ചോദിക്കണോ?',
      'Take Picture': 'ചിത്രം എടുക്കുക',
      'Yes': 'അതെ',
      'No': 'ഇല്ല',
      'Select Brand': 'ബ്രാൻഡ് തിരഞ്ഞെടുക്കുക',
      'Marlboro': 'നൈക്ക്',
      'Dunhill': 'ഹെർമിസ്',
      'Pan masala': 'ലൂയി വിറ്റൺ',
      'Select Option': 'ഓപ്ഷൻ തിരഞ്ഞെടുക്കുക',
      'Select Amount': 'തുക തിരഞ്ഞെടുക്കുക',
      'Upload Image': 'ചിത്രം അപ്ലോഡ് ചെയ്യുക',
      'Sign Out': 'സൈൻ ഔട്ട്',
      'Language': 'ഭാഷ',
      'Preferences': 'മുൻഗണനകൾ',
      'Rate the App': 'ആപ്പ് റേറ്റുചെയ്യുക',
      'Help': 'സഹായം',
      'Support': 'പിന്തുണ',
      'Rewards': 'പ്രതിഫലം',
      'You have 568 points': 'നിങ്ങൾക്ക് 568 പോയിന്റുണ്ട്',
      'Benefits': 'ആനുകൂല്യങ്ങൾ',
      'Notifications': 'അറിയിപ്പുകൾ',
      'Accounts': 'അക്കൗണ്ടുകൾ',
      'Personal Information': 'സ്വകാര്യ വിവരം',
      'Your Account': 'നിങ്ങളുടെ അക്കൗണ്ട്',
      'Profile': 'പ്രൊഫൈൽ',
      'Date Of Birth': 'ജനനത്തീയതി',
      'United Arab Emirates': 'യുണൈറ്റഡ് അറബ് എമിറേറ്റ്സ്',
      'Saved Payment Methods': 'സംരക്ഷിച്ച പേയ്‌മെന്റ് രീതികൾ',
      'Add New': 'പുതിയത് ചേർക്കുക',
      'Add': 'ചേർക്കുക',
      'Add Payment Method': 'പേയ്‌മെന്റ് രീതി ചേർക്കുക',
      'First Abu Dhabi Bank': 'ആദ്യത്തെ അബുദാബി ബാങ്ക്',
      'Dubai Islamic Bank': 'ദുബായ് ഇസ്ലാമിക് ബാങ്ക്',
      'Etisalat Wallet': 'എത്തിസലാത്ത് വാലെ',
      'Magnati': 'മാഗ്നതി',
      'Bank Account': 'ബാങ്ക് അക്കൗണ്ട്',
      'E-Wallet': 'ഇ-വാലറ്റ്',
      'Today\'s Notification': 'ഇന്നത്തെ അറിയിപ്പ്',
      'Approved Review': 'അംഗീകൃത അവലോകനം',
      'Your Given Review about Shop is approved from Admin.':
      'ഷോപ്പിനെ കുറിച്ചുള്ള നിങ്ങളുടെ അവലോകനം അഡ്മിനിൽ നിന്ന് അംഗീകരിക്കപ്പെട്ടിരിക്കുന്നു.',
      'Send via crypto network': 'ക്രിപ്‌റ്റോ നെറ്റ്‌വർക്ക് വഴി അയയ്ക്കുക',
      'Send via email/ Phone/ Pay ID': 'ഇമെയിൽ / ഫോൺ / പേ ഐഡി വഴി അയയ്ക്കുക',
      'send to a known crypto address\nvia crypto network':
      'ക്രിപ്‌റ്റോ നെറ്റ്‌വർക്ക് വഴി \n അറിയപ്പെടുന്ന ഒരു ക്രിപ്‌റ്റോ വിലാസത്തിലേക്ക് അയയ്‌ക്കുക',
      'Recipient must be a Algorthmi user':
      'സ്വീകർത്താവ് അൽഗോർത്മി ഉപയോക്താവായിരിക്കണം',
      'Coins': 'നാണയങ്ങൾ',
      'Cash': 'പണം',
      'You currently have': 'നിങ്ങൾക്ക് നിലവിൽ ഉണ്ട്',
      'Link Account': 'അക്കൗണ്ട് ലിങ്ക് ചെയ്യുക',
      'Transfer to Bank/E-Wallet': 'ബാങ്ക് / ഇ-വാലറ്റിലേക്ക് ട്രാൻസ്ഫർ ചെയ്യുക',
      'Withdraw': 'പിൻവലിക്കുക',
      'Transfer': 'കൈമാറ്റം',
      'Withdrawal Money': 'പണം പിൻവലിക്കൽ',
      'Al Ansari Exchange': 'അൽ അൻസാരി എക്സ്ചേഞ്ച്',
    },
    'de_DE': {
      'Select your preferred language': 'Selecteer uw voorkeurstaal',
      'Login': 'Anmeldung',
      'Enter Your Email': 'Voer uw e-mailadres in',
      'Please enter a valid email':
      'Gelieve een geldig e-mailadres in te vullen',
      'Enter Your Password': 'Voer uw wachtwoord in',
      'Password not be empty!': 'Wachtwoord mag niet leeg zijn!',
      'Password must be greater than 5 character!':
      'Wachtwoord moet langer zijn dan 5 tekens!',
      'Forgot Password?': 'Wachtwoord vergeten?',
      'Forgot Password': 'Wachtwoord vergeten',
      'Don’t have an account ?   ': 'Heb je geen account?   ',
      'Sign Up': 'Aanmelden',
      'Don’t worry! It happens. Please enter the email address associated with your account.':
      'Maak je geen zorgen! Het gebeurt. Voer het e-mailadres in dat aan uw account is gekoppeld.',
      'Submit': 'Indienen',
      'Reset Password': 'Reset wachtwoord',
      'Your new password must be different from previous used passwords.':
      'Uw nieuwe wachtwoord moet verschillen van eerder gebruikte wachtwoorden.',
      'Password': 'Wachtwoord',
      'Confirm Password': 'Bevestig wachtwoord',
      'Select Role': 'Rol selecteren',
      'Freelancers': 'zzp\'ers',
      'Shop Owner': 'Winkeleigenaar',
      'Already have an account ?   ': 'Heb je al een account?   ',
      'Upload Selfie': 'Selfie uploaden',
      'Take Selfie for starting Questionnaire':
      'Neem een selfie met een winkelnaamlabel om de vragenlijst te starten',
      'Take Selfie': 'Maak een selfie',
      'Take / Upload': 'Nemen / uploaden',
      'Upload from Gallery': 'Uploaden vanuit Galerij',
      'Next': 'Volgende',
      'Scan Your ID': 'Scannen Sie \nIhren Ausweis',
      'Personal Details\nConfirmation': 'Persönliche Daten\nBestätigung',
      'Mobile & Email\nConfirmation': 'Handy & E-Mail\nBestätigung',
      'Enter Verification\nCode': 'Bestätigungscode \neingeben',
      'Scan Your License': 'Scannen Sie \nIhre Lizenz',
      'License Details\nConfirmation': 'Lizenzdetails\nBestätigung',
      'Confirm': 'Bestätigen',
      'Verify': 'Verifizieren',
      'Back': 'Zurück',
      'Please confirm your\nPersonal Information':
      'Bitte bestätigen Sie Ihre \n persönlichen Daten',
      'ID Number': 'ID-Nummer',
      'ID Number not be empty!': 'ID-Nummer darf nicht leer sein!',
      'Full Name': 'Vollständiger Name',
      'Full Name not be empty!': 'Vollständiger Name ist nicht leer!',
      'Nationality': 'Staatsangehörigkeit',
      'Nationality not be empty!': 'Nationalität nicht leer sein!',
      'Scan the back of your ': 'Scannen Sie die Rückseite Ihres ',
      'Emirates ID': 'Emirates-ID',
      'Start Scanning': 'Scannen starten',
      'Card Number': 'Kartennummer',
      'Card Number not be empty!': 'Kartennummer darf nicht leer sein!',
      'Please Place the back of your\nTrade License inside the frame':
      'Bitte legen Sie die Rückseite \nIhres Gewerbescheins in den Rahmen',
      'Scan License': 'Lizenz scannen',
      'Please Place the back of your\nEmirates ID inside the frame':
      'Bitte legen Sie die Rückseite Ihres\n Emirates-Ausweises in den Rahmen',
      'Scan Card': 'Karte scannen',
      'Date of Birth': 'Geburtsdatum',
      'Date of Birth not be empty!': 'Geburtsdatum ist nicht leer!',
      'Expiry Date': 'Verfallsdatum',
      'Expiry Date not be empty!': 'Ablaufdatum ist nicht leer!',
      'Gender': 'Geschlecht',
      'Male': 'Männlich',
      'Female': 'Weiblich',
      'Other': 'Andere',
      'Gender not be empty!': 'Geschlecht ist nicht leer!',
      'Please provide your Mobile Phone Number and Email to continue':
      'Bitte geben Sie Ihre Mobiltelefonnummer und E-Mail-Adresse an, um fortzufahren',
      'Phone Number': 'Telefonnummer',
      'Email': 'Email',
      'Please enter the OTP Code\nwe sent you':
      'Bitte geben Sie den OTP-Code ein,\nden wir Ihnen gesendet haben',
      'I did not receive the OTP': 'Ich habe das OTP nicht erhalten',
      'Resend Code': 'Code erneut senden',
      'Please confirm your\nLicense Information':
      'Bitte bestätigen Sie Ihre \nLizenzinformationen',
      'License No': 'Lizenznummer',
      'License No not be empty!': 'Lizenznummer darf nicht leer sein!',
      'Trade Name': 'Handelsname',
      'Trade Name not be empty!': 'Handelsname darf nicht leer sein!',
      'Scan the back of your\n': 'Scannen Sie die Rückseite Ihres\n',
      'Trade License': 'Handelslizenz',
      'WellDone': 'Gut gemacht',
      'Congratulations': 'Glückwunsch',
      'You have successfully registered\nyour ALGORITHMI account':
      'Sie haben Ihr ALGORITHMI-Konto \n erfolgreich registriert',
      'You have successfully added\nyour':
      'Sie haben \n Ihre erfolgreich hinzugefügt',
      'You\'re upload file and Submitted\nfor review':
      'Sie haben die Datei hochgeladen und \n zur Überprüfung eingereicht',
      'Your survey has been Finished and\nSubmitted for review':
      'Ihre Umfrage wurde abgeschlossen und \n zur Überprüfung eingereicht',
      'Go to Dashboard': 'Gehen Sie zum Dashboard',
      'Dashboard': 'Armaturenbrett',
      'Wallet': 'Geldbörse',
      'Settings': 'Einstellung',
      'Muhammad Usman': 'Muhammad Usman',
      'Verified Account': 'Verifiziertes Konto',
      'Current location: ': 'Aktueller Standort: ',
      'Al Barai, Dubai': 'Al-Barai, Dubai',
      'Account Type: ': 'Konto Typ: ',
      'Shop Keeper': 'Ladenbesitzer',
      'Member Status: ': 'Mitgliedsstatus: ',
      'Bronze': 'Bronze',
      'Questioners: ': 'Fragesteller: ',
      '3/5 Approved': '3/5 genehmigt',
      'Questionnaire': 'Fragebogen',
      '1) Is there Storage available.\n2) # of counters.\n3) Sales of tobacco.\n4) Attach image of tobacco shelf.\n5) Ask shop keep top selling brands.\n6) Sales of energy drinks.':
      '1) Verfügt der Standort über ein POS-System? \n 2) Anzahl der Zähler. \n 3) Verkauf von Tabak. \n 4) Bild des Tabakregals anhängen. \n 5) Fragen Sie den Shop, um die meistverkauften Marken zu behalten. \n 6) Verkauf von Energydrinks.',
      'Accept': 'Akzeptieren',
      'Cancel': 'Stornieren',
      'Start New Survey': 'Neue Umfrage starten',
      'Last Survey Conducted on 26 Nov 2022':
      'Letzte Umfrage durchgeführt am 26. November 2022',
      'Upload Invoices': 'Rechnungen hochladen',
      'Last Invoice Uploaded on 26 Nov 2022':
      'Letzte Rechnung hochgeladen am 26. November 2022',
      'Upload Stock Report': 'Bestandsbericht hochladen',
      'Last Report Uploaded on 26 Nov 2022':
      'Letzter Bericht hochgeladen am 26. November 2022',
      'Let’s Start...': 'Lasst uns beginnen...',
      'Quick Supermarket, Majan': 'Schneller Supermarkt, Majan',
      'Your slot has been blocked for\n60 min':
      'Ihr Slot wurde für \n60 Minuten gesperrt',
      'Start Survey Now!': 'Jetzt Umfrage starten!',
      'Upload File': 'Datei hochladen',
      'Select File': 'Datei aussuchen',
      'Question': 'Frage',
      'Is there Storage available?':
      'Verfügt der Standort über ein Kassensystem?',
      'Work on Wholesale activity?': 'Gesamtzahl der Kassenschalter?',
      'How many number of employees?': 'Verkaufen sie Tabak?',
      'Attach image of tobacco shelf.': 'Bild des Tabakregals anhängen.',
      'Ask shopkeeper top selling brands?':
      'Fragen Sie den Ladenbesitzer nach den meistverkauften Marken?',
      'Take Picture': 'Ein Bild machen',
      'Yes': 'Ja',
      'No': 'NEIN',
      'Select Brand': 'Marke auswählen',
      'Marlboro': 'Marlboro',
      'Dunhill': 'Dunhill',
      'Pan masala': 'Pan masala',
      'Select Option': 'Wähle eine Option',
      'Select Amount': 'Wählen Sie Betrag',
      'Upload Image': 'Bild hochladen',
      'Sign Out': 'Austragen',
      'Language': 'Sprache',
      'Preferences': 'Einstellungen',
      'Rate the App': 'Bewerten Sie die App',
      'Help': 'Hilfe',
      'Support': 'Unterstützung',
      'Rewards': 'Belohnung',
      'You have 568 points': 'Sie haben 568 Punkte',
      'Benefits': 'Vorteile',
      'Notifications': 'Benachrichtigungen',
      'Accounts': 'Konten',
      'Personal Information': 'Persönliche Angaben',
      'Your Account': 'Ihr Konto',
      'Profile': 'Profil',
      'Date Of Birth': 'Geburtsdatum',
      'United Arab Emirates': 'Vereinigte Arabische Emirate',
      'Saved Payment Methods': 'Gespeicherte Zahlungsmethoden',
      'Add New': 'Neue hinzufügen',
      'Add': 'Hinzufügen',
      'Add Payment Method': 'Zahlungsmethode hinzufügen',
      'First Abu Dhabi Bank': 'Erste Abu Dhabi Bank',
      'Dubai Islamic Bank': 'Islamische Bank von Dubai',
      'Etisalat Wallet': 'Etisalat Walle',
      'Magnati': 'Magnati',
      'Bank Account': 'Bankkonto',
      'E-Wallet': 'E-Wallet',
      'Today\'s Notification': 'Heutige Benachrichtigung',
      'Approved Review': 'Genehmigte Bewertung',
      'Your Given Review about Shop is approved from Admin.':
      'Ihre abgegebene Bewertung über den Shop wurde vom Administrator genehmigt.',
      'Send via crypto network': 'Über Krypto-Netzwerk senden',
      'Send via email/ Phone/ Pay ID': 'Senden Sie per E-Mail / Telefon / Pay ID',
      'send to a known crypto address\nvia crypto network':
      'Senden an eine bekannte Krypto-Adresse \n über ein Krypto-Netzwerk',
      'Recipient must be a Algorthmi user':
      'Der Empfänger muss ein Algorthmi-Benutzer sein',
      'Coins': 'Münzen',
      'Cash': 'Kasse',
      'You currently have': 'Derzeit hast due',
      'Link Account': 'Konto verbinden',
      'Transfer to Bank/E-Wallet': 'Überweisung an Bank / E-Wallet',
      'Withdraw': 'Zurückziehen',
      'Transfer': 'Überweisen',
      'Withdrawal Money': 'Auszahlungsgeld',
      'Al Ansari Exchange': 'Al-Ansari-Börse',
    },
    'ne_IN': {
      'Select your preferred language': 'आफ्नो मनपर्ने भाषा चयन गर्नुहोस्',
      'Login': 'लग - इन',
      'Enter Your Email': 'आफ्नो इमेल प्रविष्ट गर्नुहोस्',
      'Please enter a valid email': 'कृपया मान्य इमेल प्रविष्ट गर्नुहोस्',
      'Enter Your Password': 'आफ्नो पासवर्ड प्रविष्ट गर्नुहोस्',
      'Password not be empty!': 'पासवर्ड खाली नहोस्!',
      'Password must be greater than 5 character!':
      'पासवर्ड 5 वर्ण भन्दा ठूलो हुनुपर्छ!',
      'Forgot Password?': 'पासवर्ड भुल्नु भयो?',
      'Forgot Password': 'पासवर्ड भुल्नु भयो',
      'Don’t have an account ?   ': 'खाता छैन?   ',
      'Sign Up': 'साइन अप',
      'Don’t worry! It happens. Please enter the email address associated with your account.':
      'चिन्ता नगर्नुहोस्! यस्तो हुन्छ। कृपया आफ्नो खातासँग सम्बन्धित इमेल ठेगाना प्रविष्ट गर्नुहोस्।',
      'Submit': 'पेश गर्नुहोस्',
      'Reset Password': 'पासवर्ड रिसेट',
      'Your new password must be different from previous used passwords.':
      'तपाईंको नयाँ पासवर्ड अघिल्लो प्रयोग गरिएका पासवर्डहरू भन्दा फरक हुनुपर्छ।',
      'Password': 'पासवर्ड',
      'Confirm Password': 'पासवर्ड सुनिश्चित गर्नुहोस',
      'Select Role': 'भूमिका चयन गर्नुहोस्',
      'Freelancers': 'फ्रीलान्सरहरू',
      'Shop Owner': 'पसल मालिक',
      'Already have an account ?   ': 'पहिले नै खाता छ?   ',
      'Upload Selfie': 'सेल्फी अपलोड गर्नुहोस्',
      'Take Selfie for starting Questionnaire':
      'प्रश्नावली सुरु गर्नको लागि पसलको नाम लेबलको साथ सेल्फी लिनुहोस्',
      'Take Selfie': 'सेल्फी लिनुहोस्',
      'Take / Upload': 'लिनुहोस् / अपलोड गर्नुहोस्',
      'Upload from Gallery': 'ग्यालरीबाट अपलोड गर्नुहोस्',
      'Next': 'अर्को',
      'Scan Your ID': 'आफ्नो आईडी \nस्क्यान गर्नुहोस्',
      'Personal Details\nConfirmation': 'व्यक्तिगत विवरणहरू\nपुष्टि',
      'Mobile & Email\nConfirmation': 'मोबाइल र इमेल\nपुष्टि',
      'Enter Verification\nCode': 'प्रमाणीकरण\nकोड प्रविष्ट गर्नुहोस्',
      'Scan Your License': 'तपाईंको लाइसेन्स \nस्क्यान गर्नुहोस्',
      'License Details\nConfirmation': 'इजाजतपत्र विवरणहरू\nपुष्टि',
      'Confirm': 'पुष्टि गर्नुहोस्',
      'Verify': 'प्रमाणित गर्नुहोस्',
      'Back': 'पछाडि',
      'Please confirm your\nPersonal Information':
      'कृपया आफ्नो \n व्यक्तिगत जानकारी पुष्टि गर्नुहोस्',
      'ID Number': 'आईडी नम्बर',
      'ID Number not be empty!': 'आईडी नम्बर खाली छैन!',
      'Full Name': 'पुरा नाम',
      'Full Name not be empty!': 'पूरा नाम खाली छैन!',
      'Nationality': 'राष्ट्रियता',
      'Nationality not be empty!': 'राष्ट्रियता खाली छैन!',
      'Scan the back of your ': 'आफ्नो पछाडि स्क्यान गर्नुहोस् ',
      'Emirates ID': 'एमिरेट्स आईडी',
      'Start Scanning': 'स्क्यान सुरु गर्नुहोस्',
      'Card Number': 'कार्ड नम्बर',
      'Card Number not be empty!': 'कार्ड नम्बर खाली छैन!',
      'Please Place the back of your\nTrade License inside the frame':
      'कृपया आफ्नो ट्रेड लाइसेन्सको \nपछाडि फ्रेम भित्र राख्नुहोस्',
      'Scan License': 'स्क्यान लाइसेन्स',
      'Please Place the back of your\nEmirates ID inside the frame':
      'कृपया आफ्नो एमिरेट्स आईडीको\n पछाडि फ्रेम भित्र राख्नुहोस्',
      'Scan Card': 'स्क्यान कार्ड',
      'Date of Birth': 'जन्म मिति',
      'Date of Birth not be empty!': 'जन्म मिति खाली छैन!',
      'Expiry Date': 'म्याद सकिने मिति',
      'Expiry Date not be empty!': 'म्याद सकिने मिति खाली छैन!',
      'Gender': 'लिङ्ग',
      'Male': 'पुरुष',
      'Female': 'महिला',
      'Other': 'अन्य',
      'Gender not be empty!': 'लिङ्ग खाली छैन!',
      'Please provide your Mobile Phone Number and Email to continue':
      'जारी राख्न कृपया आफ्नो मोबाइल फोन नम्बर र इमेल प्रदान गर्नुहोस्',
      'Phone Number': 'फोन नम्बर',
      'Email': 'इमेल',
      'Please enter the OTP Code\nwe sent you':
      'कृपया OTP कोड प्रविष्ट गर्नुहोस्\nहामीले तपाईंलाई पठाउनुभएको छ',
      'I did not receive the OTP': 'मैले OTP प्राप्त गरेन',
      'Resend Code': 'कोड पुन: पठाउनुहोस्',
      'Please confirm your\nLicense Information':
      'कृपया आफ्नो \nलाइसेन्स जानकारी पुष्टि गर्नुहोस्',
      'License No': 'इजाजतपत्र नं',
      'License No not be empty!': 'लाइसेन्स खाली छैन!',
      'Trade Name': 'व्यापार नाम',
      'Trade Name not be empty!': 'व्यापार नाम खाली हुनु हुँदैन!',
      'Scan the back of your\n': 'आफ्नो पछाडि स्क्यान गर्नुहोस्\n',
      'Trade License': 'ट्रेड लाइसेन्स',
      'WellDone': 'राम्रो काम',
      'Congratulations': 'बधाई छ',
      'You have successfully registered\nyour ALGORITHMI account':
      'तपाईंले सफलतापूर्वक आफ्नो ALGORITHMI खाता \n दर्ता गर्नुभएको छ',
      'You have successfully added\nyour':
      'तपाईंले सफलतापूर्वक थप्नुभएको छ \n तपाईंको',
      'You\'re upload file and Submitted\nfor review':
      'तपाईंले फाइल अपलोड गर्नुभयो र समीक्षाको लागि \n पेस गर्नुभयो',
      'Your survey has been Finished and\nSubmitted for review':
      'तपाईंको सर्वेक्षण समाप्त भयो र \n समीक्षाको लागि पेश गरियो',
      'Go to Dashboard': 'ड्यासबोर्डमा जानुहोस्',
      'Dashboard': 'ड्यासबोर्ड',
      'Wallet': 'वालेट',
      'Settings': 'सेटिङ',
      'Muhammad Usman': 'मोहम्मद उस्मान',
      'Verified Account': 'प्रमाणित खाता',
      'Current location: ': 'वर्तमान स्थान: ',
      'Al Barai, Dubai': 'अल बाराई, दुबई',
      'Account Type: ': 'खाताको प्रकार: ',
      'Shop Keeper': 'पसल किपर',
      'Member Status: ': 'सदस्य स्थिति: ',
      'Bronze': 'कांस्य',
      'Questioners: ': 'प्रश्नकर्ताहरू: ',
      '3/5 Approved': '3/5 स्वीकृत',
      'Questionnaire': 'प्रश्नावली',
      '1) Is there Storage available.\n2) # of counters.\n3) Sales of tobacco.\n4) Attach image of tobacco shelf.\n5) Ask shop keep top selling brands.\n6) Sales of energy drinks.':
      '1) के स्थानमा POS प्रणाली छ। \n २) # काउन्टरहरू। \n 3) सुर्तीको बिक्री। \n 4) तंबाकू शेल्फको छवि संलग्न गर्नुहोस्। \n 5) पसललाई शीर्ष बिक्री हुने ब्रान्डहरू राख्न सोध्नुहोस्। \n ६) ऊर्जा पेयको बिक्री।',
      'Accept': 'स्वीकार गर्नुहोस्',
      'Cancel': 'रद्द गर्नुहोस्',
      'Start New Survey': 'नयाँ सर्वेक्षण सुरु गर्नुहोस्',
      'Last Survey Conducted on 26 Nov 2022':
      'पछिल्लो सर्वेक्षण २६ नोभेम्बर २०२२ मा गरिएको थियो',
      'Upload Invoices': 'इनभ्वाइसहरू अपलोड गर्नुहोस्',
      'Last Invoice Uploaded on 26 Nov 2022':
      'अन्तिम इनभ्वाइस २६ नोभेम्बर २०२२ मा अपलोड गरिएको थियो',
      'Upload Stock Report': 'स्टक रिपोर्ट अपलोड गर्नुहोस्',
      'Last Report Uploaded on 26 Nov 2022':
      'पछिल्लो रिपोर्ट २६ नोभेम्बर २०२२ मा अपलोड गरिएको थियो',
      'Let’s Start...': 'सुरु गरौँ...',
      'Quick Supermarket, Majan': 'द्रुत सुपरमार्केट, माजन',
      'Your slot has been blocked for\n60 min':
      'तपाईंको स्लट \n60 मिनेटको लागि अवरुद्ध गरिएको छ',
      'Start Survey Now!': 'अब सर्वेक्षण सुरु गर्नुहोस्!',
      'Upload File': 'फाइल अपलोड गर्नुहोस्',
      'Select File': 'फाइल चयन गर्नुहोस्',
      'Question': 'प्रश्न',
      'Is there Storage available?': 'के स्थानमा POS प्रणाली छ?',
      'Work on Wholesale activity?': 'नगद काउन्टरहरूको कुल संख्या?',
      'How many number of employees?': 'के तिनीहरू सुर्ती बेच्छन्?',
      'Attach image of tobacco shelf.':
      'तंबाकू शेल्फको छवि संलग्न गर्नुहोस्।',
      'Ask shopkeeper top selling brands?':
      'पसललाई सबैभन्दा बढी बिक्री हुने ब्रान्डहरू सोध्नुहोस्?',
      'Take Picture': 'तस्वीर लिनुहोस्',
      'Yes': 'हो',
      'No': 'छैन',
      'Select Brand': 'ब्रान्ड चयन गर्नुहोस्',
      'Marlboro': 'नाइके',
      'Dunhill': 'हर्मिस',
      'Pan masala': 'लुइसभिटन',
      'Select Option': 'विकल्प चयन गर्नुहोस्',
      'Select Amount': 'रकम चयन गर्नुहोस्',
      'Upload Image': 'छवि अपलोड गर्नुहोस्',
      'Sign Out': 'साइन आउट गर्नुहोस्',
      'Language': 'भाषा',
      'Preferences': 'प्राथमिकताहरू',
      'Rate the App': 'एप मूल्याङ्कन गर्नुहोस्',
      'Help': 'मद्दत गर्नुहोस्',
      'Support': 'समर्थन',
      'Rewards': 'पुरस्कारहरू',
      'You have 568 points': 'तपाईंसँग 568 अंक छ',
      'Benefits': 'फाइदाहरू',
      'Notifications': 'सूचनाहरू',
      'Accounts': 'खाताहरू',
      'Personal Information': 'व्यक्तिगत जानकारी',
      'Your Account': 'तपाईंको खाता',
      'Profile': 'प्रोफाइल',
      'Date Of Birth': 'जन्म मिति',
      'United Arab Emirates': 'संयुक्त अरब इमिरेट्स',
      'Saved Payment Methods': 'सुरक्षित भुक्तानी विधिहरू',
      'Add New': 'नयाँ थप्नुहोस्',
      'Add': 'थप्नुहोस्',
      'Add Payment Method': 'भुक्तानी विधि थप्नुहोस्',
      'First Abu Dhabi Bank': 'पहिलो अबु धाबी बैंक',
      'Dubai Islamic Bank': 'दुबई इस्लामिक बैंक',
      'Etisalat Wallet': 'एतिसलात वाले',
      'Magnati': 'Magnati',
      'Bank Account': 'बैंक खाता',
      'E-Wallet': 'ई-वालेट',
      'Today\'s Notification': 'आजको सूचना',
      'Approved Review': 'स्वीकृत समीक्षा',
      'Your Given Review about Shop is approved from Admin.':
      'पसलको बारेमा तपाईंको दिईएको समीक्षा प्रशासकबाट अनुमोदन गरिएको छ।',
      'Send via crypto network': 'क्रिप्टो नेटवर्क मार्फत पठाउनुहोस्',
      'Send via email/ Phone/ Pay ID': 'इमेल/फोन/भुक्तानी आईडी मार्फत पठाउनुहोस्',
      'send to a known crypto address\nvia crypto network':
      'क्रिप्टो नेटवर्क मार्फत \n ज्ञात क्रिप्टो ठेगानामा पठाउनुहोस्',
      'Recipient must be a Algorthmi user':
      'प्रापक एल्गोरथमी प्रयोगकर्ता हुनुपर्छ',
      'Coins': 'सिक्का',
      'Cash': 'नगद',
      'You currently have': 'तपाईंसँग हाल छ',
      'Link Account': 'खाता लिङ्क गर्नुहोस्',
      'Transfer to Bank/E-Wallet': 'बैंक / ई-वालेटमा स्थानान्तरण गर्नुहोस्',
      'Withdraw': 'निकाल्नु',
      'Transfer': 'स्थानान्तरण',
      'Withdrawal Money': 'निकासी पैसा',
      'Al Ansari Exchange': 'अल अन्सारी एक्सचेन्ज',
    },
    'bn_BD': {
      'Select your preferred language': 'আপনার পছন্দের ভাষা নির্বাচন করুন',
      'Login': 'প্রবেশ করুন',
      'Enter Your Email': 'তুমার ইমেইল প্রবেশ করাও',
      'Please enter a valid email': 'একটি বৈধ ইমেইল প্রবেশ করুন',
      'Enter Your Password': 'আপনার পাসওয়ার্ড লিখুন',
      'Password not be empty!': 'পাসওয়ার্ড খালি থাকবে না!',
      'Password must be greater than 5 character!':
      'পাসওয়ার্ড 5 অক্ষরের বেশি হতে হবে!',
      'Forgot Password?': 'পাসওয়ার্ড ভুলে গেছেন?',
      'Forgot Password': 'পাসওয়ার্ড ভুলে গেছেন',
      'Don’t have an account ?   ': 'একটি অ্যাকাউন্ট নেই?   ',
      'Sign Up': 'নিবন্ধন করুন',
      'Don’t worry! It happens. Please enter the email address associated with your account.':
      'চিন্তা করবেন না! এটা ঘটে। আপনার অ্যাকাউন্টের সাথে যুক্ত ইমেইল ঠিকানা লিখুন।',
      'Submit': 'জমা দিন',
      'Reset Password': 'পাসওয়ার্ড রিসেট করুন',
      'Your new password must be different from previous used passwords.':
      'আপনার নতুন পাসওয়ার্ড আগের ব্যবহৃত পাসওয়ার্ড থেকে আলাদা হতে হবে।',
      'Password': 'পাসওয়ার্ড',
      'Confirm Password': 'পাসওয়ার্ড নিশ্চিত করুন',
      'Select Role': 'ভূমিকা নির্বাচন করুন',
      'Freelancers': 'ফ্রিল্যান্সার',
      'Shop Owner': 'দোকান মালিক',
      'Already have an account ?   ': 'ইতিমধ্যে একটি সদস্যপদ আছে?   ',
      'Upload Selfie': 'সেলফি আপলোড করুন',
      'Take Selfie for starting Questionnaire':
      'প্রশ্নাবলী শুরু করার জন্য দোকানের নামের লেবেল সহ সেলফি নিন',
      'Take Selfie': 'সেলফি তুলুন',
      'Take / Upload': 'নিন/আপলোড করুন',
      'Upload from Gallery': 'গ্যালারি থেকে আপলোড করুন',
      'Next': 'পরবর্তী',
      'Scan Your ID': 'আপনার আইডি \nস্ক্যান করুন',
      'Personal Details\nConfirmation': 'ব্যক্তিগত বিবরণ\nনিশ্চিতকরণ',
      'Mobile & Email\nConfirmation': 'মোবাইল এবং ইমেল\nনিশ্চিতকরণ',
      'Enter Verification\nCode': 'যাচাইকরণ\nকোড লিখুন',
      'Scan Your License': 'আপনার লাইসেন্স \nস্ক্যান করুন',
      'License Details\nConfirmation': 'লাইসেন্সের বিবরণ\nনিশ্চিতকরণ',
      'Confirm': 'নিশ্চিত করুন',
      'Verify': 'যাচাই করুন',
      'Back': 'পেছনে',
      'Please confirm your\nPersonal Information':
      'অনুগ্রহ করে আপনার \n ব্যক্তিগত তথ্য নিশ্চিত করুন',
      'ID Number': 'আইডি নাম্বার',
      'ID Number not be empty!': 'আইডি নম্বর খালি থাকবে না!',
      'Full Name': 'পুরো নাম',
      'Full Name not be empty!': 'পুরো নাম খালি নেই!',
      'Nationality': 'জাতীয়তা',
      'Nationality not be empty!': 'জাতীয়তা খালি হবে না!',
      'Scan the back of your ': 'আপনার পিছনে স্ক্যান করুন ',
      'Emirates ID': 'এমিরেটস আইডি',
      'Start Scanning': 'স্ক্যান করা শুরু করুন',
      'Card Number': 'কার্ড নম্বর',
      'Card Number not be empty!': 'কার্ড নম্বর খালি হবে না!',
      'Please Place the back of your\nTrade License inside the frame':
      'অনুগ্রহ করে আপনার ট্রেড লাইসেন্সের \nপিছনে ফ্রেমের ভিতরে রাখুন',
      'Scan License': 'স্ক্যান লাইসেন্স',
      'Please Place the back of your\nEmirates ID inside the frame':
      'অনুগ্রহ করে আপনার এমিরেটস \nআইডির পিছনে ফ্রেমের ভিতরে রাখুন',
      'Scan Card': 'স্ক্যান কার্ড',
      'Date of Birth': 'জন্ম তারিখ',
      'Date of Birth not be empty!': 'জন্ম তারিখ খালি নেই!',
      'Expiry Date': 'মেয়াদ শেষ হওয়ার তারিখ',
      'Expiry Date not be empty!': 'মেয়াদ শেষ হওয়ার তারিখ খালি নেই!',
      'Gender': 'লিঙ্গ',
      'Male': 'পুরুষ',
      'Female': 'মহিলা',
      'Other': 'অন্যান্য',
      'Gender not be empty!': 'লিঙ্গ খালি নয়!',
      'Please provide your Mobile Phone Number and Email to continue':
      'চালিয়ে যেতে আপনার মোবাইল ফোন নম্বর এবং ইমেল প্রদান করুন',
      'Phone Number': 'ফোন নম্বর',
      'Email': 'ইমেইল',
      'Please enter the OTP Code\nwe sent you':
      'অনুগ্রহ করে OTP কোড লিখুন\nআমরা আপনাকে পাঠিয়েছি',
      'I did not receive the OTP': 'আমি ওটিপি পাইনি',
      'Resend Code': 'পুনরায় পাঠানো কোড',
      'Please confirm your\nLicense Information':
      'অনুগ্রহ করে আপনার \nলাইসেন্স তথ্য নিশ্চিত করুন',
      'License No': 'লাইসেন্স নং',
      'License No not be empty!': 'লাইসেন্স খালি হবে না!',
      'Trade Name': 'বাণিজ্যিক নাম',
      'Trade Name not be empty!': 'ট্রেডের নাম খালি হবে না!',
      'Scan the back of your\n': 'আপনার পিছনে স্ক্যান করুন',
      'Trade License': 'ট্রেড লাইসেন্স',
      'WellDone': 'সাবাশ',
      'Congratulations': 'অভিনন্দন',
      'You have successfully registered\nyour ALGORITHMI account':
      'আপনি সফলভাবে আপনার ALGORITHMI অ্যাকাউন্ট \n নিবন্ধন করেছেন৷',
      'You have successfully added\nyour':
      'আপনি সফলভাবে যোগ করেছেন \n আপনার',
      'You\'re upload file and Submitted\nfor review':
      'আপনি ফাইল আপলোড করছেন এবং পর্যালোচনার জন্য \n জমা দিয়েছেন',
      'Your survey has been Finished and\nSubmitted for review':
      'আপনার সমীক্ষা শেষ হয়েছে এবং \n পর্যালোচনার জন্য জমা দেওয়া হয়েছে৷',
      'Go to Dashboard': 'ড্যাশবোর্ড এ যান',
      'Dashboard': 'ড্যাশবোর্ড',
      'Wallet': 'ওয়ালেট',
      'Settings': 'বিন্যাস',
      'Muhammad Usman': 'মুহাম্মদ উসমান',
      'Verified Account': 'যাচাইকৃত একাউন্ট',
      'Current location: ': 'এখন যেখানে আছ: ',
      'Al Barai, Dubai': 'আল বারাই, দুবাই',
      'Account Type: ': 'অ্যাকাউন্ট ধরন: ',
      'Shop Keeper': 'দোকান কিপার',
      'Member Status: ': 'সদস্যের অবস্থা: ',
      'Bronze': 'ব্রোঞ্জ',
      'Questioners: ': 'প্রশ্নকর্তা: ',
      '3/5 Approved': '3/5 অনুমোদিত',
      'Questionnaire': 'প্রশ্নপত্র',
      '1) Is there Storage available.\n2) # of counters.\n3) Sales of tobacco.\n4) Attach image of tobacco shelf.\n5) Ask shop keep top selling brands.\n6) Sales of energy drinks.':
      '1) অবস্থানের একটি POS সিস্টেম আছে কি? \n 2) # কাউন্টার। \n 3) তামাক বিক্রি। \n 4) তামাকের শেলফের ছবি সংযুক্ত করুন। \n 5) দোকানে সবচেয়ে বেশি বিক্রি হওয়া ব্র্যান্ড রাখতে বলুন। \n 6) শক্তি পানীয় বিক্রি।',
      'Accept': 'গ্রহণ করুন',
      'Cancel': 'বাতিল করুন',
      'Start New Survey': 'নতুন জরিপ শুরু করুন',
      'Last Survey Conducted on 26 Nov 2022':
      '26 নভেম্বর 2022-এ শেষ সমীক্ষা করা হয়েছিল',
      'Upload Invoices': 'চালান আপলোড করুন',
      'Last Invoice Uploaded on 26 Nov 2022':
      '26 নভেম্বর 2022-এ শেষ চালান আপলোড করা হয়েছে',
      'Upload Stock Report': 'আপলোড স্টক রিপোর্ট',
      'Last Report Uploaded on 26 Nov 2022':
      '26 নভেম্বর 2022-এ শেষ রিপোর্ট আপলোড করা হয়েছে',
      'Let’s Start...': 'চল শুরু করি...',
      'Quick Supermarket, Majan': 'কুইক সুপার মার্কেট, মাজন',
      'Your slot has been blocked for\n60 min':
      'আপনার স্লট \n60 মিনিটের জন্য ব্লক করা হয়েছে',
      'Start Survey Now!': 'এখনই জরিপ শুরু করুন!',
      'Upload File': 'ফাইল আপলোড করুন',
      'Select File': 'নথি নির্বাচন',
      'Question': 'প্রশ্ন',
      'Is there Storage available?':
      'অবস্থান একটি POS সিস্টেম আছে?',
      'Work on Wholesale activity?': 'ক্যাশ কাউন্টার মোট সংখ্যা?',
      'v?': 'তারা কি তামাক বিক্রি করে?',
      'Attach image of tobacco shelf.': 'তামাকের শেলফের ছবি সংযুক্ত করুন।',
      'Ask shopkeeper top selling brands?':
      'দোকানদারকে জিজ্ঞাসা করুন শীর্ষ বিক্রিত ব্র্যান্ড?',
      'Take Picture': 'ছবি তোলা',
      'Yes': 'হ্যাঁ',
      'No': 'না',
      'Select Brand': 'ব্র্যান্ড নির্বাচন করুন',
      'Marlboro': 'নাইকি',
      'Dunhill': 'হার্মিস',
      'Pan masala': 'লুই ভিটন',
      'Select Option': 'বিকল্প নির্বাচন',
      'Select Amount': 'পরিমাণ নির্বাচন করুন',
      'Upload Image': 'চিত্র আপলোড',
      'Sign Out': 'সাইন আউট',
      'Language': 'ভাষা',
      'Preferences': 'পছন্দসমূহ',
      'Rate the App': 'অ্যাপ্লিকেশন রেট',
      'Help': 'সাহায্য',
      'Support': 'সমর্থন',
      'Rewards': 'পুরস্কার',
      'You have 568 points': 'আপনার 568 পয়েন্ট আছে',
      'Benefits': 'সুবিধা',
      'Notifications': 'বিজ্ঞপ্তি',
      'Accounts': 'হিসাব',
      'Personal Information': 'ব্যক্তিগত তথ্য',
      'Your Account': 'আপনার অ্যাকাউন্ট',
      'Profile': 'প্রোফাইল',
      'Date Of Birth': 'জন্ম তারিখ',
      'United Arab Emirates': 'সংযুক্ত আরব আমিরাত',
      'Saved Payment Methods': 'সংরক্ষিত পেমেন্ট পদ্ধতি',
      'Add New': 'নতুন যোগ করুন',
      'Add': 'যোগ করুন',
      'Add Payment Method': 'পেমেন্ট পদ্ধতি যোগ করুন',
      'First Abu Dhabi Bank': 'প্রথম আবুধাবি ব্যাংক',
      'Dubai Islamic Bank': 'দুবাই ইসলামিক ব্যাংক',
      'Etisalat Wallet': 'এতিসালাত ওয়ালে',
      'Magnati': 'মাগনাতি',
      'Bank Account': 'ব্যাংক হিসাব',
      'E-Wallet': 'ই-ওয়ালেট',
      'Today\'s Notification': 'আজকের বিজ্ঞপ্তি',
      'Approved Review': 'অনুমোদিত পর্যালোচনা',
      'Your Given Review about Shop is approved from Admin.':
      'দোকান সম্পর্কে আপনার দেওয়া পর্যালোচনা অ্যাডমিনের কাছ থেকে অনুমোদিত হয়েছে।',
      'Send via crypto network': 'ক্রিপ্টো নেটওয়ার্কের মাধ্যমে পাঠান',
      'Send via email/ Phone/ Pay ID': 'ইমেইল/ফোন/পে আইডির মাধ্যমে পাঠান',
      'send to a known crypto address\nvia crypto network':
      'একটি পরিচিত ক্রিপ্টো ঠিকানায় পাঠান \n ক্রিপ্টো নেটওয়ার্কের মাধ্যমে',
      'Recipient must be a Algorthmi user':
      'প্রাপক অবশ্যই অ্যালগর্থমি ব্যবহারকারী হতে হবে',
      'Coins': 'কয়েন',
      'Cash': 'নগদ',
      'You currently have': 'আপনি বর্তমানে আছে',
      'Link Account': 'অ্যাকাউন্ট লিঙ্ক করুন',
      'Transfer to Bank/E-Wallet': 'ব্যাংক/ই-ওয়ালেটে স্থানান্তর করুন',
      'Withdraw': 'প্রত্যাহার করুন',
      'Transfer': 'স্থানান্তর',
      'Withdrawal Money': 'টাকা তোলা',
      'Al Ansari Exchange': 'আল আনসারী এক্সচেঞ্জ',
    },
    'ur_PK': {
      'Select your preferred language': 'اپنی پسند کی زبان منتخب کریں۔',
      'Login': 'لاگ ان کریں',
      'Enter Your Email': 'اپنا ای میل درج کریں۔',
      'Please enter a valid email': 'ایک درست ای میل درج کریں',
      'Enter Your Password': 'اپنا پاس ورڈ درج کریں',
      'Password not be empty!': 'پاس ورڈ خالی نہ ہو!',
      'Password must be greater than 5 character!':
      'پاس ورڈ 5 حروف سے بڑا ہونا چاہیے!',
      'Forgot Password?': 'پاسورڈ بھول گے؟',
      'Forgot Password': 'پاسورڈ بھول گے',
      'Don’t have an account ?   ': 'اکاؤنٹ نہیں ہے؟   ',
      'Sign Up': 'سائن اپ',
      'Don’t worry! It happens. Please enter the email address associated with your account.':
      'فکر مت کرو! یہ ہوتا ہے. براہ کرم اپنے اکاؤنٹ سے وابستہ ای میل ایڈریس درج کریں۔',
      'Submit': 'جمع کرائیں',
      'Reset Password': 'پاس ورڈ ری سیٹ',
      'Your new password must be different from previous used passwords.':
      'آپ کا نیا پاس ورڈ پہلے استعمال شدہ پاس ورڈز سے مختلف ہونا چاہیے۔',
      'Password': 'پاس ورڈ',
      'Confirm Password': 'پاس ورڈ کی تصدیق کریں۔',
      'Select Role': 'کردار منتخب کریں۔',
      'Freelancers': 'فری لانسرز',
      'Shop Owner': 'دکان کے مالک',
      'Already have an account ?   ': 'پہلے سے ہی اکاؤنٹ ہے؟   ',
      'Upload Selfie': 'سیلفی اپ لوڈ کریں',
      'Take Selfie for starting Questionnaire':
      'سوالنامہ شروع کرنے کے لیے دکان کے نام کے لیبل کے ساتھ سیلفی لیں۔',
      'Take Selfie': 'سیلفی لیں۔',
      'Take / Upload': 'لیں / اپ لوڈ کریں۔',
      'Upload from Gallery': 'گیلری سے اپ لوڈ کریں۔',
      'Next': 'اگلے',
      'Scan Your ID': 'اپنی آئی ڈی \nاسکین کریں',
      'Personal Details\nConfirmation': 'ذاتی تفصیلات\nتصدیق',
      'Mobile & Email\nConfirmation': 'موبائل اور ای میل\nتصدیق',
      'Enter Verification\nCode': 'تصدیقی کوڈ \nداخل کریں',
      'Scan Your License': 'اپنا لائسنس\nاسکین کریں',
      'License Details\nConfirmation': 'لائسنس کی تفصیلات\nتصدیق',
      'Confirm': 'تصدیق کریں۔',
      'Verify': 'تصدیق کریں۔',
      'Back': 'پیچھے',
      'Please confirm your\nPersonal Information':
      'براہ کرم اپنی  ذاتی\n معلومات کی تصدیق کریں',
      'ID Number': 'شناختی نمبر',
      'ID Number not be empty!': 'شناختی نمبر خالی نہ ہو!',
      'Full Name': 'پورا نام',
      'Full Name not be empty!': 'پورا نام خالی نہیں ہے!',
      'Nationality': 'قومیت',
      'Nationality not be empty!': 'قومیت خالی نہ ہو!',
      'Scan the back of your ': 'اپنے پیچھے کو اسکین کریں۔ ',
      'Emirates ID': 'ایمریٹس آئی ڈی',
      'Start Scanning': 'اسکیننگ شروع کریں',
      'Card Number': 'کارڈ نمبر',
      'Card Number not be empty!': 'کارڈ نمبر خالی نہ ہو!',
      'Please Place the back of your\nTrade License inside the frame':
      'براہ کرم اپنے تجارتی لائسنس کا \nپچھلا حصہ فریم کے اندر رکھیں',
      'Scan License': 'اسکین لائسنس',
      'Please Place the back of your\nEmirates ID inside the frame':
      'براہ کرم اپنے ایمریٹس آئی ڈی کا\n پچھلا حصہ فریم کے اندر رکھیں',
      'Scan Card': 'اسکین کارڈ',
      'Date of Birth': 'پیدائش کی تاریخ',
      'Date of Birth not be empty!': 'تاریخ پیدائش خالی نہیں ہے!',
      'Expiry Date': 'میعاد ختم ہونے کی تاریخ',
      'Expiry Date not be empty!': 'میعاد ختم ہونے کی تاریخ خالی نہیں ہے!',
      'Gender': 'صنف',
      'Male': 'مرد',
      'Female': 'عورت',
      'Other': 'دیگر',
      'Gender not be empty!': 'جنس خالی نہیں ہے!',
      'Please provide your Mobile Phone Number and Email to continue':
      'جاری رکھنے کے لیے براہ کرم اپنا موبائل فون نمبر اور ای میل فراہم کریں۔',
      'Phone Number': 'فون نمبر',
      'Email': 'ای میل',
      'Please enter the OTP Code\nwe sent you':
      'براہ کرم وہ OTP کوڈ درج کریں جو ہم نے آپ کو بھیجا ہے۔',
      'I did not receive the OTP': 'مجھے OTP موصول نہیں ہوا۔',
      'Resend Code': 'کوڈ پھر سے بھیجو',
      'Please confirm your\nLicense Information':
      'براہ کرم اپنے \nلائسنس کی معلومات کی تصدیق کریں۔',
      'License No': 'لائسنس نمبر',
      'License No not be empty!': 'لائسنس نہیں خالی نہیں!',
      'Trade Name': 'تجارتی نام',
      'Trade Name not be empty!': 'تجارتی نام خالی نہ ہو!',
      'Scan the back of your\n': 'اپنے پیچھے کو اسکین کریں\n',
      'Trade License': 'تجارتی لائسنس',
      'WellDone': 'بہت اچھے',
      'Congratulations': 'مبارک ہو',
      'You have successfully registered\nyour ALGORITHMI account':
      'آپ نے کامیابی سے اپنا ALGORITHMI اکاؤنٹ رجسٹر کر لیا ہے۔',
      'You have successfully added\nyour':
      'آپ نے کامیابی سے\nاپنا شامل کر لیا ہے۔',
      'You\'re upload file and Submitted\nfor review':
      'آپ نے فائل اپ لوڈ کر دی ہے اور جائزہ کے لیے\nجمع کر دی ہے۔',
      'Your survey has been Finished and\nSubmitted for review':
      'آپ کا سروے مکمل ہو چکا ہے اور جائزہ کے لیے جمع کر دیا گیا ہے۔',
      'Go to Dashboard': 'ڈیش بورڈ پر جائیں',
      'Dashboard': 'ڈیش بورڈ',
      'Wallet': 'پرس',
      'Settings': 'ترتیبات',
      'Muhammad Usman': 'محمد عثمان',
      'Verified Account': 'تصدیق شدہ اکاؤنٹ',
      'Current location: ': 'موجودہ مقام: ',
      'Al Barai, Dubai': 'البرائی، دبئی',
      'Account Type: ': 'اکاؤنٹ کی اقسام: ',
      'Shop Keeper': 'شاپ کیپر',
      'Member Status: ': 'رکن کی حیثیت: ',
      'Bronze': 'کانسی',
      'Questioners: ': 'سائل: ',
      '3/5 Approved': '3/5 منظور شدہ',
      'Questionnaire': 'سوالنامہ',
      '1) Is there Storage available.\n2) # of counters.\n3) Sales of tobacco.\n4) Attach image of tobacco shelf.\n5) Ask shop keep top selling brands.\n6) Sales of energy drinks.':
      '1) کیا مقام پر POS سسٹم ہے؟ \n 2) # کاؤنٹرز۔ \n 3) تمباکو کی فروخت۔ \n 4) تمباکو کے شیلف کی تصویر منسلک کریں۔ \n 5) دکان سے پوچھیں کہ سب سے زیادہ فروخت ہونے والے برانڈز رکھیں۔ \n 6) انرجی ڈرنکس کی فروخت۔',
      'Accept': 'قبول کریں۔',
      'Cancel': 'منسوخ کریں۔',
      'Start New Survey': 'نیا سروے شروع کریں۔',
      'Last Survey Conducted on 26 Nov 2022':
      'آخری سروے 26 نومبر 2022 کو کیا گیا۔',
      'Upload Invoices': 'رسیدیں اپ لوڈ کریں۔',
      'Last Invoice Uploaded on 26 Nov 2022':
      'آخری انوائس 26 نومبر 2022 کو اپ لوڈ کی گئی۔',
      'Upload Stock Report': 'اسٹاک رپورٹ اپ لوڈ کریں۔',
      'Last Report Uploaded on 26 Nov 2022':
      'آخری رپورٹ 26 نومبر 2022 کو اپ لوڈ کی گئی۔',
      'Let’s Start...': 'شروع کرتے ہیں...',
      'Quick Supermarket, Majan': 'کوئیک سپر مارکیٹ، مجن',
      'Your slot has been blocked for\n60 min':
      'آپ کا سلاٹ \n60 منٹ کے لیے بلاک کر دیا گیا ہے۔',
      'Start Survey Now!': 'ابھی سروے شروع کریں!',
      'Upload File': 'اپ لوڈ فائل',
      'Select File': 'فائل کو منتخب کریں۔',
      'Question': 'سوال',
      'Is there Storage available?': 'کیا مقام پر POS سسٹم ہے؟',
      'Work on Wholesale activity?': 'کیش کاؤنٹرز کی کل تعداد؟',
      'How many number of employees?': 'کیا وہ تمباکو بیچتے ہیں؟',
      'Attach image of tobacco shelf.':
      'تمباکو کے شیلف کی تصویر منسلک کریں۔',
      'Ask shopkeeper top selling brands?':
      'دکاندار سب سے زیادہ فروخت ہونے والے برانڈز سے پوچھیں؟',
      'Take Picture': 'تصویر لے',
      'Yes': 'جی ہاں',
      'No': 'نہیں',
      'Select Brand': 'برانڈ منتخب کریں۔',
      'Marlboro': 'نائکی',
      'Dunhill': 'ہرمیس',
      'Pan masala': 'لوئس ووٹن',
      'Select Option': 'اختیار منتخب کریں۔',
      'Select Amount': 'رقم منتخب کریں۔',
      'Upload Image': 'تصویر انٹرنیٹ پر ڈالنا',
      'Sign Out': 'باہر جائیں',
      'Language': 'زبان',
      'Preferences': 'ترجیحات',
      'Rate the App': 'ایپ کی درجہ بندی کریں۔',
      'Help': 'مدد',
      'Support': 'حمایت',
      'Rewards': 'انعامات',
      'You have 568 points': 'آپ کے 568 پوائنٹس ہیں۔',
      'Benefits': 'فوائد',
      'Notifications': 'اطلاعات',
      'Accounts': 'اکاؤنٹس',
      'Personal Information': 'ذاتی معلومات',
      'Your Account': 'آپ کا کھاتہ',
      'Profile': 'پروفائل',
      'Date Of Birth': 'پیدائش کی تاریخ',
      'United Arab Emirates': 'متحدہ عرب امارات',
      'Saved Payment Methods': 'محفوظ شدہ ادائیگی کے طریقے',
      'Add New': 'نیا شامل کریں',
      'Add': 'شامل کریں۔',
      'Add Payment Method': 'ادائیگی کا طریقہ شامل کریں۔',
      'First Abu Dhabi Bank': 'پہلا ابوظہبی بینک',
      'Dubai Islamic Bank': 'دبئی اسلامک بینک',
      'Etisalat Wallet': 'اتصالات والے',
      'Magnati': 'میگناتی',
      'Bank Account': 'بینک اکاؤنٹ',
      'E-Wallet': 'ای والیٹ',
      'Today\'s Notification': 'آج کا نوٹیفکیشن',
      'Approved Review': 'منظور شدہ جائزہ',
      'Your Given Review about Shop is approved from Admin.':
      'شاپ کے بارے میں آپ کا دیا ہوا جائزہ ایڈمن سے منظور شدہ ہے۔',
      'Send via crypto network': 'کرپٹو نیٹ ورک کے ذریعے بھیجیں۔',
      'Send via email/ Phone/ Pay ID': 'ای میل/ فون/ پے آئی ڈی کے ذریعے بھیجیں۔',
      'send to a known crypto address\nvia crypto network':
      'کرپٹو نیٹ ورک کے ذریعے ایک معروف کرپٹو\n ایڈریس پر بھیجیں۔',
      'Recipient must be a Algorthmi user':
      'وصول کنندہ ایک الگورتھمی صارف ہونا چاہیے۔',
      'Coins': 'سکے',
      'Cash': 'نقد',
      'You currently have': 'آپ کے پاس فی الحال ہے۔',
      'Link Account': 'اکاؤنٹ لنک کریں۔',
      'Transfer to Bank/E-Wallet': 'بینک / ای والیٹ میں منتقل کریں۔t',
      'Withdraw': 'واپس لینا',
      'Transfer': 'منتقلی',
      'Withdrawal Money': 'رقم نکالنا',
      'Al Ansari Exchange': 'الانصاری ایکسچینج',
    },
  };
}